// <auto-generated />
using System;
using System.Collections.Generic;
using System.Net;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using URegister.Core.Data;

#nullable disable

namespace URegister.Core.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.DataProtection.EntityFrameworkCore.DataProtectionKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FriendlyName")
                        .HasColumnType("text")
                        .HasColumnName("friendly_name");

                    b.Property<string>("Xml")
                        .HasColumnType("text")
                        .HasColumnName("xml");

                    b.HasKey("Id")
                        .HasName("pk_data_protection_keys");

                    b.ToTable("data_protection_keys", (string)null);
                });

            modelBuilder.Entity("RulesEngine.Models.Rule", b =>
                {
                    b.Property<string>("RuleName")
                        .HasColumnType("text")
                        .HasColumnName("rule_name");

                    b.Property<string>("Actions")
                        .HasColumnType("text")
                        .HasColumnName("actions");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean")
                        .HasColumnName("enabled");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<string>("Expression")
                        .HasColumnType("text")
                        .HasColumnName("expression");

                    b.Property<string>("Operator")
                        .HasColumnType("text")
                        .HasColumnName("operator");

                    b.Property<string>("Properties")
                        .HasColumnType("text")
                        .HasColumnName("properties");

                    b.Property<int>("RuleExpressionType")
                        .HasColumnType("integer")
                        .HasColumnName("rule_expression_type");

                    b.Property<string>("RuleNameFK")
                        .HasColumnType("text")
                        .HasColumnName("rule_name_fk");

                    b.Property<string>("SuccessEvent")
                        .HasColumnType("text")
                        .HasColumnName("success_event");

                    b.Property<string>("WorkflowName")
                        .HasColumnType("text")
                        .HasColumnName("workflow_name");

                    b.HasKey("RuleName")
                        .HasName("pk_rules");

                    b.HasIndex("RuleNameFK")
                        .HasDatabaseName("ix_rules_rule_name_fk");

                    b.HasIndex("WorkflowName")
                        .HasDatabaseName("ix_rules_workflow_name");

                    b.ToTable("rules", (string)null);
                });

            modelBuilder.Entity("RulesEngine.Models.ScopedParam", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Expression")
                        .HasColumnType("text")
                        .HasColumnName("expression");

                    b.Property<string>("RuleName")
                        .HasColumnType("text")
                        .HasColumnName("rule_name");

                    b.Property<string>("WorkflowName")
                        .HasColumnType("text")
                        .HasColumnName("workflow_name");

                    b.HasKey("Name")
                        .HasName("pk_scoped_param");

                    b.HasIndex("RuleName")
                        .HasDatabaseName("ix_scoped_param_rule_name");

                    b.HasIndex("WorkflowName")
                        .HasDatabaseName("ix_scoped_param_workflow_name");

                    b.ToTable("scoped_param", (string)null);
                });

            modelBuilder.Entity("RulesEngine.Models.Workflow", b =>
                {
                    b.Property<string>("WorkflowName")
                        .HasColumnType("text")
                        .HasColumnName("workflow_name");

                    b.Property<int>("RuleExpressionType")
                        .HasColumnType("integer")
                        .HasColumnName("rule_expression_type");

                    b.HasKey("WorkflowName")
                        .HasName("pk_workflows");

                    b.ToTable("workflows", (string)null);
                });

            modelBuilder.Entity("URegister.Core.Data.Models.Common.BlanksTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasComment("Идентификатор");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("code")
                        .HasComment("Код");

                    b.Property<string>("Content")
                        .HasColumnType("text")
                        .HasColumnName("content")
                        .HasComment("Съдържание на бланка");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by")
                        .HasComment("Създадена от");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_on")
                        .HasComment("Дата на създаване");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("timestamptz")
                        .HasColumnName("deleted_on")
                        .HasComment("Дата на изтриване");

                    b.Property<int>("FormParentId")
                        .HasColumnType("integer")
                        .HasColumnName("form_parent_id")
                        .HasComment("Идентификатор на тип форма");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active")
                        .HasComment("Дали записът е активен");

                    b.Property<Guid>("ModifiedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("modified_by_user_id")
                        .HasComment("Идентификатор на потребителят променил последно записа");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("timestamptz")
                        .HasColumnName("modified_on")
                        .HasComment("Дата на последна промяна");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name")
                        .HasComment("Име");

                    b.Property<int?>("ServiceId")
                        .HasColumnType("integer")
                        .HasColumnName("service_id")
                        .HasComment("Идентификатор на услуга");

                    b.Property<int>("SourceType")
                        .HasColumnType("integer")
                        .HasColumnName("source_type")
                        .HasComment("Идентификатор на услуга");

                    b.HasKey("Id")
                        .HasName("pk_blanks_templates");

                    b.HasIndex("ServiceId")
                        .HasDatabaseName("ix_blanks_templates_service_id");

                    b.ToTable("blanks_templates", (string)null);
                });

            modelBuilder.Entity("URegister.Core.Data.Models.Common.CustomView", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasComment("Индентификатор");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("timestamptz")
                        .HasColumnName("deleted_on")
                        .HasComment("Дата на изтриване");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active")
                        .HasComment("Дали записът е активен");

                    b.Property<Guid>("ModifiedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("modified_by_user_id")
                        .HasComment("Идентификатор на потребителят променил последно записа");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("timestamptz")
                        .HasColumnName("modified_on")
                        .HasComment("Дата на последна промяна");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name")
                        .HasComment("Наименование");

                    b.Property<List<string>>("SelectedColumns")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("selected_columns")
                        .HasComment("Избрани полета за колони");

                    b.HasKey("Id")
                        .HasName("pk_custom_views");

                    b.ToTable("custom_views", null, t =>
                        {
                            t.HasComment("Вписвания");
                        });
                });

            modelBuilder.Entity("URegister.Core.Data.Models.Common.DeadlineDay", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasComment("Идентификатор");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DayTypeId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("day_type_id")
                        .HasComment("Работни/календарни дни");

                    b.Property<int>("Days")
                        .HasColumnType("integer")
                        .HasColumnName("days")
                        .HasComment("Срок за изпълнение на услуга/дни");

                    b.Property<string>("DeadlineTypeId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("deadline_type_id")
                        .HasComment("Вид срок за изпълнение на услуга");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("timestamptz")
                        .HasColumnName("deleted_on")
                        .HasComment("Дата на изтриване");

                    b.Property<int>("FormParentId")
                        .HasColumnType("integer")
                        .HasColumnName("form_parent_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active")
                        .HasComment("Дали записът е активен");

                    b.Property<Guid>("ModifiedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("modified_by_user_id")
                        .HasComment("Идентификатор на потребителят променил последно записа");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("timestamptz")
                        .HasColumnName("modified_on")
                        .HasComment("Дата на последна промяна");

                    b.Property<int?>("ServiceId")
                        .HasColumnType("integer")
                        .HasColumnName("service_id");

                    b.HasKey("Id")
                        .HasName("pk_deadline_days");

                    b.HasIndex("ServiceId")
                        .HasDatabaseName("ix_deadline_days_service_id");

                    b.ToTable("deadline_days", null, t =>
                        {
                            t.HasComment("Срокове за изпълнение на услуга");
                        });
                });

            modelBuilder.Entity("URegister.Core.Data.Models.Common.FileMetadata", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasComment("Идентификатор");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("timestamptz")
                        .HasColumnName("deleted_on")
                        .HasComment("Дата на изтриване");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("Oписание");

                    b.Property<DateTime?>("EFormDateOfFill")
                        .HasColumnType("timestamptz")
                        .HasColumnName("e_form_date_of_fill")
                        .HasComment("Дата на попълване на е-формата, ако файлът е заявление подадено чрез е-форма");

                    b.Property<Guid?>("EFormId")
                        .HasColumnType("uuid")
                        .HasColumnName("e_form_id")
                        .HasComment("Идентификатор на е-форма, ако файлът е заявление подадено чрез е-форма");

                    b.Property<Guid>("FileId")
                        .HasColumnType("uuid")
                        .HasColumnName("file_id")
                        .HasComment("Идентификатор на файла в хранилището");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("file_name")
                        .HasComment("Име на файла");

                    b.Property<int>("FileSourceTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("file_source_type_id")
                        .HasComment("Идентификатор на  източник");

                    b.Property<string>("Hash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("hash")
                        .HasComment("Хеш сума");

                    b.Property<string>("HashingAlgorithm")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("hashing_algorithm")
                        .HasComment("Алгоритъм за изчисляване на хеш сума");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active")
                        .HasComment("Дали записът е активен");

                    b.Property<Guid>("ModifiedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("modified_by_user_id")
                        .HasComment("Идентификатор на потребителят променил последно записа");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("timestamptz")
                        .HasColumnName("modified_on")
                        .HasComment("Дата на последна промяна");

                    b.Property<Guid?>("ProcessId")
                        .HasColumnType("uuid")
                        .HasColumnName("process_id")
                        .HasComment("Идентификатор на заявена услуга, по-която е качен файла");

                    b.Property<string>("Signature")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("signature")
                        .HasComment("Подпис");

                    b.Property<string>("SourceId")
                        .HasColumnType("text")
                        .HasColumnName("source_id")
                        .HasComment("Идентификатор на източник");

                    b.HasKey("Id")
                        .HasName("pk_file_metadata");

                    b.HasIndex("ProcessId")
                        .HasDatabaseName("ix_file_metadata_process_id");

                    b.ToTable("file_metadata", null, t =>
                        {
                            t.HasComment("Инфорация за качен от потребител файл");
                        });
                });

            modelBuilder.Entity("URegister.Core.Data.Models.Common.Form", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasComment("Индентификатор");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ApprovalStatus")
                        .HasColumnType("integer")
                        .HasColumnName("approval_status")
                        .HasComment("Статус на одобрение на формата");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("timestamptz")
                        .HasColumnName("deleted_on")
                        .HasComment("Дата на изтриване");

                    b.Property<string>("FieldConfiguration")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("field_configuration")
                        .HasComment("Конфигурация на полетата");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active")
                        .HasComment("Дали записът е активен");

                    b.Property<Guid>("ModifiedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("modified_by_user_id")
                        .HasComment("Идентификатор на потребителят променил последно записа");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("timestamptz")
                        .HasColumnName("modified_on")
                        .HasComment("Дата на последна промяна");

                    b.Property<int?>("ParentId")
                        .HasColumnType("integer")
                        .HasColumnName("parent_id")
                        .HasComment("Идентификатор на първата версия на формата");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("purpose")
                        .HasComment("Предназначение на формата");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("title")
                        .HasComment("Заглавие на формата");

                    b.HasKey("Id")
                        .HasName("pk_forms");

                    b.HasIndex("ParentId")
                        .HasDatabaseName("ix_forms_parent_id");

                    b.ToTable("forms", null, t =>
                        {
                            t.HasComment("Съдържа конфигурацияна на полетата във форма");
                        });
                });

            modelBuilder.Entity("URegister.Core.Data.Models.Common.ProcessDelivery", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasComment("Идентификатор");

                    b.Property<string>("ChannelId")
                        .HasColumnType("text")
                        .HasColumnName("channel_id")
                        .HasComment("Начин на връчване");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("timestamptz")
                        .HasColumnName("deleted_on")
                        .HasComment("Дата на изтриване");

                    b.Property<DateTime?>("DeliveryDate")
                        .HasColumnType("timestamptz")
                        .HasColumnName("delivery_date")
                        .HasComment("Дата на връчване");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("Oписание");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active")
                        .HasComment("Дали записът е активен");

                    b.Property<Guid>("ModifiedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("modified_by_user_id")
                        .HasComment("Идентификатор на потребителят променил последно записа");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("timestamptz")
                        .HasColumnName("modified_on")
                        .HasComment("Дата на последна промяна");

                    b.Property<Guid>("ProcessId")
                        .HasColumnType("uuid")
                        .HasColumnName("process_id")
                        .HasComment("Идентификатор на заявена услуга");

                    b.Property<string>("SourceId")
                        .HasColumnType("text")
                        .HasColumnName("source_id")
                        .HasComment("Идентификатор на източник");

                    b.Property<int>("SourceTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("source_type_id")
                        .HasComment("Идентификатор на  източник");

                    b.Property<int>("StatusId")
                        .HasColumnType("integer")
                        .HasColumnName("status_id")
                        .HasComment("Статус");

                    b.HasKey("Id")
                        .HasName("pk_process_delivery");

                    b.HasIndex("ProcessId")
                        .HasDatabaseName("ix_process_delivery_process_id");

                    b.ToTable("process_delivery", null, t =>
                        {
                            t.HasComment("Информация за връчяане откази/удостоверения/указания");
                        });
                });

            modelBuilder.Entity("URegister.Core.Data.Models.Common.PublicFieldTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasComment("Идентификатор");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .HasColumnType("text")
                        .HasColumnName("content")
                        .HasComment("Съдържание на бланка");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by")
                        .HasComment("Създадена от");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_on")
                        .HasComment("Дата на създаване");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("timestamptz")
                        .HasColumnName("deleted_on")
                        .HasComment("Дата на изтриване");

                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("field_name")
                        .HasComment("Име напле в Json");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active")
                        .HasComment("Дали записът е активен");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("label")
                        .HasComment("Наименование на публично поле");

                    b.Property<Guid>("ModifiedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("modified_by_user_id")
                        .HasComment("Идентификатор на потребителят променил последно записа");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("timestamptz")
                        .HasColumnName("modified_on")
                        .HasComment("Дата на последна промяна");

                    b.Property<int>("OrderNum")
                        .HasColumnType("integer")
                        .HasColumnName("order_num")
                        .HasComment("Поредност");

                    b.HasKey("Id")
                        .HasName("pk_public_field_templates");

                    b.ToTable("public_field_templates", (string)null);
                });

            modelBuilder.Entity("URegister.Core.Data.Models.Common.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasComment("Индентификатор");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("timestamptz")
                        .HasColumnName("deleted_on")
                        .HasComment("Дата на изтриване");

                    b.Property<string>("EFormCode")
                        .HasColumnType("text")
                        .HasColumnName("e_form_code")
                        .HasComment("Референтен номер на услуга (РНУ)");

                    b.Property<int>("FormParentId")
                        .HasColumnType("integer")
                        .HasColumnName("form_parent_id")
                        .HasComment("Идентификатор на тип форма");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active")
                        .HasComment("Дали записът е активен");

                    b.Property<Guid>("ModifiedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("modified_by_user_id")
                        .HasComment("Идентификатор на потребителят променил последно записа");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("timestamptz")
                        .HasColumnName("modified_on")
                        .HasComment("Дата на последна промяна");

                    b.Property<int>("ServiceTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("service_type_id")
                        .HasComment("Идентификатор на тип услуга");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("title")
                        .HasComment("Име на услугата");

                    b.HasKey("Id")
                        .HasName("pk_services");

                    b.ToTable("services", null, t =>
                        {
                            t.HasComment("Услуга в регистъра");
                        });
                });

            modelBuilder.Entity("URegister.Core.Data.Models.Common.ServiceStep", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasComment("Индентификатор");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("timestamptz")
                        .HasColumnName("deleted_on")
                        .HasComment("Дата на изтриване");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active")
                        .HasComment("Дали записът е активен");

                    b.Property<Guid>("ModifiedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("modified_by_user_id")
                        .HasComment("Идентификатор на потребителят променил последно записа");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("timestamptz")
                        .HasColumnName("modified_on")
                        .HasComment("Дата на последна промяна");

                    b.Property<int>("OrderNum")
                        .HasColumnType("integer")
                        .HasColumnName("order_num")
                        .HasComment("Поредност");

                    b.Property<int>("ServiceId")
                        .HasColumnType("integer")
                        .HasColumnName("service_id")
                        .HasComment("Идентификатор на услугата от регистъра");

                    b.Property<int>("StatusId")
                        .HasColumnType("integer")
                        .HasColumnName("status_id")
                        .HasComment("Статус");

                    b.Property<int>("StepId")
                        .HasColumnType("integer")
                        .HasColumnName("step_id")
                        .HasComment("Идентификатор на стъпка");

                    b.Property<string>("Title")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("title")
                        .HasComment("Име на стъпката");

                    b.HasKey("Id")
                        .HasName("pk_service_steps");

                    b.HasIndex("ServiceId")
                        .HasDatabaseName("ix_service_steps_service_id");

                    b.ToTable("service_steps", null, t =>
                        {
                            t.HasComment("Стъпка от услуга в регистъра");
                        });
                });

            modelBuilder.Entity("URegister.Core.Data.Models.Common.StepRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasComment("Индентификатор");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("timestamptz")
                        .HasColumnName("deleted_on")
                        .HasComment("Дата на изтриване");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active")
                        .HasComment("Дали записът е активен");

                    b.Property<Guid>("ModifiedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("modified_by_user_id")
                        .HasComment("Идентификатор на потребителят променил последно записа");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("timestamptz")
                        .HasColumnName("modified_on")
                        .HasComment("Дата на последна промяна");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id")
                        .HasComment("Идентификатор на роля");

                    b.Property<int>("ServiceStepId")
                        .HasColumnType("integer")
                        .HasColumnName("service_step_id")
                        .HasComment("Идентификатор на стъпка");

                    b.HasKey("Id")
                        .HasName("pk_step_role");

                    b.HasIndex("ServiceStepId")
                        .HasDatabaseName("ix_step_role_service_step_id");

                    b.ToTable("step_role", null, t =>
                        {
                            t.HasComment("Стъпка от услуга в регистъра");
                        });
                });

            modelBuilder.Entity("URegister.Core.Data.Models.Logging.RegixReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasComment("Индентификатор");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description")
                        .HasComment("Описание");

                    b.Property<DateTime>("EventDate")
                        .HasColumnType("timestamptz")
                        .HasColumnName("event_date")
                        .HasComment("Дата на събитието");

                    b.Property<Guid?>("RegixGuid")
                        .HasColumnType("uuid")
                        .HasColumnName("regix_guid")
                        .HasComment("Guid от Regix");

                    b.Property<string>("RegixRequestType")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("regix_request_type")
                        .HasComment("Номенклатурна стойност на тип заявка");

                    b.Property<string>("RequestData")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("request_data")
                        .HasComment("Съдържание на заявка");

                    b.Property<string>("ResponseData")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("response_data")
                        .HasComment("Съдържание на отговор");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id")
                        .HasComment("Идентификатор на потребител");

                    b.HasKey("Id")
                        .HasName("pk_regix_reports");

                    b.ToTable("regix_reports", null, t =>
                        {
                            t.HasComment("Комуникация с Regix");
                        });
                });

            modelBuilder.Entity("URegister.Core.Data.Models.Process.Instruction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasComment("Идентификатор");

                    b.Property<DateTime?>("ClosedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("closed_on");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content")
                        .HasComment("Съдържание");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on");

                    b.Property<DateTime>("DateTo")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_to");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("timestamptz")
                        .HasColumnName("deleted_on")
                        .HasComment("Дата на изтриване");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active")
                        .HasComment("Дали записът е активен");

                    b.Property<Guid>("ModifiedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("modified_by_user_id")
                        .HasComment("Идентификатор на потребителят променил последно записа");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("timestamptz")
                        .HasColumnName("modified_on")
                        .HasComment("Дата на последна промяна");

                    b.Property<Guid>("ProcessId")
                        .HasColumnType("uuid")
                        .HasColumnName("process_id")
                        .HasComment("Идентификатор на процес");

                    b.HasKey("Id")
                        .HasName("pk_instructions");

                    b.HasIndex("ProcessId")
                        .HasDatabaseName("ix_instructions_process_id");

                    b.ToTable("instructions", null, t =>
                        {
                            t.HasComment("Указания");
                        });
                });

            modelBuilder.Entity("URegister.Core.Data.Models.Process.InstructionResponse", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasComment("Идентификатор");

                    b.Property<string>("Content")
                        .HasColumnType("text")
                        .HasColumnName("content")
                        .HasComment("Съдържание");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("timestamptz")
                        .HasColumnName("deleted_on")
                        .HasComment("Дата на изтриване");

                    b.Property<Guid>("InstructionId")
                        .HasColumnType("uuid")
                        .HasColumnName("instruction_id")
                        .HasComment("Идентификатор на процес");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active")
                        .HasComment("Дали записът е активен");

                    b.Property<Guid>("ModifiedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("modified_by_user_id")
                        .HasComment("Идентификатор на потребителят променил последно записа");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("timestamptz")
                        .HasColumnName("modified_on")
                        .HasComment("Дата на последна промяна");

                    b.Property<Guid?>("ReceivedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("received_by")
                        .HasComment("Прието от");

                    b.Property<DateTime?>("ReceivedOn")
                        .HasColumnType("timestamptz")
                        .HasColumnName("received_on")
                        .HasComment("Дата на приемане");

                    b.HasKey("Id")
                        .HasName("pk_instruction_responses");

                    b.HasIndex("InstructionId")
                        .HasDatabaseName("ix_instruction_responses_instruction_id");

                    b.ToTable("instruction_responses", null, t =>
                        {
                            t.HasComment("Отговори на Указания");
                        });
                });

            modelBuilder.Entity("URegister.Core.Data.Models.Process.IntegrationFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasComment("Идентификатор");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("timestamptz")
                        .HasColumnName("deleted_on")
                        .HasComment("Дата на изтриване");

                    b.Property<Guid?>("FileMetadataId")
                        .HasColumnType("uuid")
                        .HasColumnName("file_metadata_id");

                    b.Property<string>("FileName")
                        .HasColumnType("text")
                        .HasColumnName("file_name")
                        .HasComment("Име на файл");

                    b.Property<Guid>("IntegrationFileId")
                        .HasColumnType("uuid")
                        .HasColumnName("integration_file_id")
                        .HasComment("Име на файл");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active")
                        .HasComment("Дали записът е активен");

                    b.Property<Guid>("ModifiedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("modified_by_user_id")
                        .HasComment("Идентификатор на потребителят променил последно записа");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("timestamptz")
                        .HasColumnName("modified_on")
                        .HasComment("Дата на последна промяна");

                    b.Property<Guid?>("SourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_id")
                        .HasComment("Идентификатор на връзка");

                    b.Property<int>("SourceType")
                        .HasColumnType("integer")
                        .HasColumnName("source_type")
                        .HasComment("Вид връзка");

                    b.HasKey("Id")
                        .HasName("pk_integration_files");

                    b.ToTable("integration_files", null, t =>
                        {
                            t.HasComment("Файлове от ССЕВ");
                        });
                });

            modelBuilder.Entity("URegister.Core.Data.Models.Process.Process", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasComment("Идентификатор");

                    b.Property<Guid?>("AssignedToUser")
                        .HasColumnType("uuid")
                        .HasColumnName("assigned_to_user")
                        .HasComment("Потребител, на който е присвоена услугата");

                    b.Property<DateTime?>("DeadlineDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deadline_date")
                        .HasComment("Срок за изпълнение на услуга");

                    b.Property<int>("DeadlineDay")
                        .HasColumnType("integer")
                        .HasColumnName("deadline_day")
                        .HasComment("Срок за изпълнение на услуга/дни");

                    b.Property<int>("DeadlineId")
                        .HasColumnType("integer")
                        .HasColumnName("deadline_id")
                        .HasComment("Вид срок за изпълнение на услуга");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("timestamptz")
                        .HasColumnName("deleted_on")
                        .HasComment("Дата на изтриване");

                    b.Property<Guid?>("EFormRegisteredServiceNumber")
                        .HasColumnType("uuid")
                        .HasColumnName("e_form_registered_service_number")
                        .HasComment("Номер на заявена услуга при импорт от е-форма");

                    b.Property<int>("FormId")
                        .HasColumnType("integer")
                        .HasColumnName("form_id")
                        .HasComment("Идентификатор на форма");

                    b.Property<Guid?>("FromProcessId")
                        .HasColumnType("uuid")
                        .HasColumnName("from_process_id")
                        .HasComment("Идентификатор на първоначален процес");

                    b.Property<DateTime>("IncomingDate")
                        .HasColumnType("timestamptz")
                        .HasColumnName("incoming_date")
                        .HasComment("Дата на входиране");

                    b.Property<string>("IncomingNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("incoming_number")
                        .HasComment("Входящ номер");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active")
                        .HasComment("Дали записът е активен");

                    b.Property<int?>("LastServiceStepId")
                        .HasColumnType("integer")
                        .HasColumnName("last_service_step_id")
                        .HasComment("Идентификатор на стъпка");

                    b.Property<Guid>("ModifiedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("modified_by_user_id")
                        .HasComment("Идентификатор на потребителят променил последно записа");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("timestamptz")
                        .HasColumnName("modified_on")
                        .HasComment("Дата на последна промяна");

                    b.Property<Guid>("MpriApplicantId")
                        .HasColumnType("uuid")
                        .HasColumnName("mpri_applicant_id")
                        .HasComment("Идентификатор на заявител в MasterPersonIndex");

                    b.Property<Guid>("MpriId")
                        .HasColumnType("uuid")
                        .HasColumnName("mpri_id")
                        .HasComment("Идентификатор на партида в MasterPersonIndex");

                    b.Property<DateTime?>("OldIncomingDate")
                        .HasColumnType("timestamptz")
                        .HasColumnName("old_incoming_date")
                        .HasComment("Стара дата на входиране");

                    b.Property<string>("OldIncomingNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("old_incoming_number")
                        .HasComment("Стар входящ номер");

                    b.Property<long>("OrderNumber")
                        .HasColumnType("bigint")
                        .HasColumnName("order_number")
                        .HasComment("Поредност на вписването");

                    b.Property<string>("PreferredResultDeliveryMethod")
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)")
                        .HasColumnName("preferred_result_delivery_method")
                        .HasComment("Начини на предоставяне на резултата");

                    b.Property<string>("ReasonForRejection")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("reason_for_rejection")
                        .HasComment("Причина за прекратяване");

                    b.Property<string>("ReceivedChannelId")
                        .HasColumnType("text")
                        .HasColumnName("received_channel_id")
                        .HasComment("Начин на получаване на заявлението");

                    b.Property<string>("RegisterNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("register_number")
                        .HasComment("Номер на вписване ");

                    b.Property<Guid?>("RegisteredStepId")
                        .HasColumnType("uuid")
                        .HasColumnName("registered_step_id")
                        .HasComment("Идентификатор на стъпка вписване");

                    b.Property<string>("RejectionNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("rejection_number")
                        .HasComment("Номер на отказ");

                    b.Property<int>("ServiceId")
                        .HasColumnType("integer")
                        .HasColumnName("service_id")
                        .HasComment("Идентификатор на услуга");

                    b.Property<int>("StatusId")
                        .HasColumnType("integer")
                        .HasColumnName("status_id")
                        .HasComment("Статус");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id")
                        .HasComment("Идентификатор на администрация");

                    b.HasKey("Id")
                        .HasName("pk_processes");

                    b.HasIndex("FormId")
                        .HasDatabaseName("ix_processes_form_id");

                    b.HasIndex("FromProcessId")
                        .HasDatabaseName("ix_processes_from_process_id");

                    b.HasIndex("LastServiceStepId")
                        .HasDatabaseName("ix_processes_last_service_step_id");

                    b.HasIndex("ServiceId")
                        .HasDatabaseName("ix_processes_service_id");

                    b.ToTable("processes", null, t =>
                        {
                            t.HasComment("Заявени услуги");
                        });
                });

            modelBuilder.Entity("URegister.Core.Data.Models.Process.ProcessStep", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasComment("Идентификатор");

                    b.Property<string>("CoordinationMotive")
                        .HasColumnType("text")
                        .HasColumnName("coordination_motive")
                        .HasComment("Мотиви при съгласуване");

                    b.Property<int>("CoordinationStatusId")
                        .HasColumnType("integer")
                        .HasColumnName("coordination_status_id")
                        .HasComment("Статус при съгласуване");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("timestamptz")
                        .HasColumnName("deleted_on")
                        .HasComment("Дата на изтриване");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active")
                        .HasComment("Дали записът е активен");

                    b.Property<Guid>("ModifiedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("modified_by_user_id")
                        .HasComment("Идентификатор на потребителят променил последно записа");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("timestamptz")
                        .HasColumnName("modified_on")
                        .HasComment("Дата на последна промяна");

                    b.Property<int>("OrderNum")
                        .HasColumnType("integer")
                        .HasColumnName("order_num")
                        .HasComment("Поредност на стъпка");

                    b.Property<Guid>("ProcessId")
                        .HasColumnType("uuid")
                        .HasColumnName("process_id")
                        .HasComment("Идентификатор на процес");

                    b.Property<int>("ServiceStepId")
                        .HasColumnType("integer")
                        .HasColumnName("service_step_id")
                        .HasComment("Идентификатор на стъпка");

                    b.Property<string>("StepData")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("step_data")
                        .HasComment("Информация за стъпка");

                    b.HasKey("Id")
                        .HasName("pk_process_steps");

                    b.HasIndex("ProcessId")
                        .HasDatabaseName("ix_process_steps_process_id");

                    b.HasIndex("ServiceStepId")
                        .HasDatabaseName("ix_process_steps_service_step_id");

                    b.ToTable("process_steps", null, t =>
                        {
                            t.HasComment("Стъпки към процес");
                        });
                });

            modelBuilder.Entity("URegister.Core.Data.Models.Process.RegisterItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasComment("Идентификатор");

                    b.Property<bool?>("BoolValue")
                        .HasColumnType("boolean")
                        .HasColumnName("bool_value")
                        .HasComment("Булева стойност");

                    b.Property<string>("ClValue")
                        .HasColumnType("text")
                        .HasColumnName("cl_value")
                        .HasComment("Стойност на номенклатура");

                    b.Property<DateTime?>("DateTimeValue")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_time_value")
                        .HasComment("Дата стойност");

                    b.Property<decimal?>("DecimalValue")
                        .HasColumnType("numeric")
                        .HasColumnName("decimal_value")
                        .HasComment("Числова стойност");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("timestamptz")
                        .HasColumnName("deleted_on")
                        .HasComment("Дата на изтриване");

                    b.Property<Guid>("FieldId")
                        .HasColumnType("uuid")
                        .HasColumnName("field_id")
                        .HasComment("Идентификатор на поле");

                    b.Property<int>("FieldTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("field_type_id")
                        .HasComment("Тип на поле");

                    b.Property<int>("Index")
                        .HasColumnType("integer")
                        .HasColumnName("index")
                        .HasComment("Индекс на повтарящо се поле");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active")
                        .HasComment("Дали записът е активен");

                    b.Property<bool>("IsComplex")
                        .HasColumnType("boolean")
                        .HasColumnName("is_complex")
                        .HasComment("Комплексно поле");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean")
                        .HasColumnName("is_public")
                        .HasComment("Публично поле");

                    b.Property<string>("Label")
                        .HasColumnType("text")
                        .HasColumnName("label")
                        .HasComment("Етикет на полето");

                    b.Property<Guid>("MpriId")
                        .HasColumnType("uuid")
                        .HasColumnName("mpri_id")
                        .HasComment("Идентификатор на MasterPersonIndex");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name")
                        .HasComment("Име");

                    b.Property<string>("NomenclatureType")
                        .HasColumnType("text")
                        .HasColumnName("nomenclature_type")
                        .HasComment("Тип номенклатура");

                    b.Property<Guid>("ParentFieldId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_field_id")
                        .HasComment("Идентификатор на главно поле");

                    b.Property<Guid>("ProcessId")
                        .HasColumnType("uuid")
                        .HasColumnName("process_id")
                        .HasComment("Идентификатор на процес");

                    b.Property<Guid?>("ProcessStepId")
                        .HasColumnType("uuid")
                        .HasColumnName("process_step_id")
                        .HasComment("Идентификатор на стъпка от процес");

                    b.Property<string>("RegisterNumber")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("register_number")
                        .HasComment("Номер на вписване ");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id")
                        .HasComment("Идентификатор на администрация");

                    b.Property<string>("Value")
                        .HasColumnType("text")
                        .HasColumnName("value")
                        .HasComment("Стойност");

                    b.HasKey("Id")
                        .HasName("pk_register_items");

                    b.HasIndex("ProcessId")
                        .HasDatabaseName("ix_register_items_process_id");

                    b.HasIndex("ProcessStepId")
                        .HasDatabaseName("ix_register_items_process_step_id");

                    b.ToTable("register_items", null, t =>
                        {
                            t.HasComment("Вписвания");
                        });
                });

            modelBuilder.Entity("URegister.Core.Data.Models.Register.Register", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasComment("Идентификатор");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("code")
                        .HasComment("Код на регистър");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_on")
                        .HasComment("Дата на създаване");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("timestamptz")
                        .HasColumnName("deleted_on")
                        .HasComment("Дата на изтриване");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description")
                        .HasComment("Описание");

                    b.Property<string>("IdentitySecurityLevel")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("identity_security_level")
                        .HasComment("Ниво на осигуреност на средствата за електронна идентификация");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active")
                        .HasComment("Дали записът е активен");

                    b.Property<string>("LegalBasis")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("legal_basis")
                        .HasComment("Правно основание");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("name")
                        .HasComment("Име на регистър");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("type")
                        .HasComment("Вид на регистъра");

                    b.Property<string>("TypeEntry")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("type_entry")
                        .HasComment("Начин на вписване");

                    b.HasKey("Id")
                        .HasName("pk_registers");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_registers_code");

                    b.ToTable("registers", null, t =>
                        {
                            t.HasComment("Регистри");
                        });
                });

            modelBuilder.Entity("URegister.Infrastructure.Data.AuditLog.Audit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasComment("Идентификатор на запис");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("action")
                        .HasComment("Действие на операцията");

                    b.Property<string>("ActivityFromId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("activity_from_id")
                        .HasComment("Идентификатор на операция");

                    b.Property<string>("ActivityId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("activity_id")
                        .HasComment("Идентификатор на операция");

                    b.Property<string>("ActivityTags")
                        .HasColumnType("jsonb")
                        .HasColumnName("activity_tags")
                        .HasComment("Допълнителна информация към операцията");

                    b.Property<string>("AssemblyName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("assembly_name")
                        .HasComment("Модул, в който е възникнала операцията");

                    b.Property<string>("Controller")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("controller")
                        .HasComment("Контролер на операцията");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created")
                        .HasComment("Дата и час на събитието (UTC)");

                    b.Property<IPAddress>("IpAddress")
                        .IsRequired()
                        .HasColumnType("inet")
                        .HasColumnName("ip_address")
                        .HasComment("IP Адрес на потребителя");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("method")
                        .HasComment("Тип на действието");

                    b.Property<string>("Parameters")
                        .HasColumnType("jsonb")
                        .HasColumnName("parameters")
                        .HasComment("Параметри на операцията");

                    b.Property<string>("PostData")
                        .HasColumnType("jsonb")
                        .HasColumnName("post_data")
                        .HasComment("Параметри на post заявката");

                    b.Property<int?>("RegisterId")
                        .HasColumnType("integer")
                        .HasColumnName("register_id")
                        .HasComment("Идентификатор на регистър");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id")
                        .HasComment("Идентификатор на администрация");

                    b.Property<string>("UserFullName")
                        .HasColumnType("text")
                        .HasColumnName("user_full_name")
                        .HasComment("Пълно име на потребител");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id")
                        .HasComment("Идентификатор на потребител");

                    b.HasKey("Id")
                        .HasName("pk_audits");

                    b.HasIndex(new[] { "Created" }, "ix_audit_created")
                        .HasDatabaseName("ix_audits_created");

                    b.HasIndex(new[] { "UserId" }, "ix_audit_user_id")
                        .HasDatabaseName("ix_audits_user_id");

                    b.ToTable("audits", null, t =>
                        {
                            t.HasComment("Одитен лог");
                        });
                });

            modelBuilder.Entity("URegister.Infrastructure.Data.AuditLog.AuditEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasComment("Идентификатор на запис");

                    b.Property<string>("AffectedColumns")
                        .HasColumnType("jsonb")
                        .HasColumnName("affected_columns")
                        .HasComment("Засегнати данни");

                    b.Property<Guid>("AuditId")
                        .HasColumnType("uuid")
                        .HasColumnName("audit_id")
                        .HasComment("Идентификатор на запис заявка");

                    b.Property<string>("NewValues")
                        .HasColumnType("jsonb")
                        .HasColumnName("new_values")
                        .HasComment("Стойности след операцията");

                    b.Property<string>("OldValues")
                        .HasColumnType("jsonb")
                        .HasColumnName("old_values")
                        .HasComment("Стойности преди операцията");

                    b.Property<string>("PrimaryKey")
                        .HasColumnType("jsonb")
                        .HasColumnName("primary_key")
                        .HasComment("Идентификатор на обект");

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("table_name")
                        .HasComment("Име на обект");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("type")
                        .HasComment("Тип на операцията");

                    b.HasKey("Id")
                        .HasName("pk_audit_entity");

                    b.HasIndex("AuditId")
                        .HasDatabaseName("ix_audit_entity_audit_id");

                    b.ToTable("audit_entity", null, t =>
                        {
                            t.HasComment("Одитен лог записи в таблица ");
                        });
                });

            modelBuilder.Entity("RulesEngine.Models.Rule", b =>
                {
                    b.HasOne("RulesEngine.Models.Rule", null)
                        .WithMany("Rules")
                        .HasForeignKey("RuleNameFK")
                        .HasConstraintName("fk_rules_rules_rule_name_fk");

                    b.HasOne("RulesEngine.Models.Workflow", null)
                        .WithMany("Rules")
                        .HasForeignKey("WorkflowName")
                        .HasConstraintName("fk_rules_workflows_workflow_name");
                });

            modelBuilder.Entity("RulesEngine.Models.ScopedParam", b =>
                {
                    b.HasOne("RulesEngine.Models.Rule", null)
                        .WithMany("LocalParams")
                        .HasForeignKey("RuleName")
                        .HasConstraintName("fk_scoped_param_rules_rule_name");

                    b.HasOne("RulesEngine.Models.Workflow", null)
                        .WithMany("GlobalParams")
                        .HasForeignKey("WorkflowName")
                        .HasConstraintName("fk_scoped_param_workflows_workflow_name");
                });

            modelBuilder.Entity("URegister.Core.Data.Models.Common.BlanksTemplate", b =>
                {
                    b.HasOne("URegister.Core.Data.Models.Common.Service", "Service")
                        .WithMany()
                        .HasForeignKey("ServiceId")
                        .HasConstraintName("fk_blanks_templates_services_service_id");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("URegister.Core.Data.Models.Common.DeadlineDay", b =>
                {
                    b.HasOne("URegister.Core.Data.Models.Common.Service", "Service")
                        .WithMany()
                        .HasForeignKey("ServiceId")
                        .HasConstraintName("fk_deadline_days_services_service_id");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("URegister.Core.Data.Models.Common.FileMetadata", b =>
                {
                    b.HasOne("URegister.Core.Data.Models.Process.Process", "Process")
                        .WithMany()
                        .HasForeignKey("ProcessId")
                        .HasConstraintName("fk_file_metadata_processes_process_id");

                    b.Navigation("Process");
                });

            modelBuilder.Entity("URegister.Core.Data.Models.Common.Form", b =>
                {
                    b.HasOne("URegister.Core.Data.Models.Common.Form", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .HasConstraintName("fk_forms_forms_parent_id");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("URegister.Core.Data.Models.Common.ProcessDelivery", b =>
                {
                    b.HasOne("URegister.Core.Data.Models.Process.Process", "Process")
                        .WithMany("ProcessDeliveries")
                        .HasForeignKey("ProcessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_process_delivery_processes_process_id");

                    b.Navigation("Process");
                });

            modelBuilder.Entity("URegister.Core.Data.Models.Common.ServiceStep", b =>
                {
                    b.HasOne("URegister.Core.Data.Models.Common.Service", "Service")
                        .WithMany("ServiceSteps")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_service_steps_services_service_id");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("URegister.Core.Data.Models.Common.StepRole", b =>
                {
                    b.HasOne("URegister.Core.Data.Models.Common.ServiceStep", "ServiceStep")
                        .WithMany("StepRoles")
                        .HasForeignKey("ServiceStepId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_step_role_service_steps_service_step_id");

                    b.Navigation("ServiceStep");
                });

            modelBuilder.Entity("URegister.Core.Data.Models.Process.Instruction", b =>
                {
                    b.HasOne("URegister.Core.Data.Models.Process.Process", "Process")
                        .WithMany("Instructions")
                        .HasForeignKey("ProcessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_instructions_processes_process_id");

                    b.Navigation("Process");
                });

            modelBuilder.Entity("URegister.Core.Data.Models.Process.InstructionResponse", b =>
                {
                    b.HasOne("URegister.Core.Data.Models.Process.Instruction", "Instruction")
                        .WithMany("InstructionResponses")
                        .HasForeignKey("InstructionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_instruction_responses_instructions_instruction_id");

                    b.Navigation("Instruction");
                });

            modelBuilder.Entity("URegister.Core.Data.Models.Process.Process", b =>
                {
                    b.HasOne("URegister.Core.Data.Models.Common.Form", "Form")
                        .WithMany()
                        .HasForeignKey("FormId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_processes_forms_form_id");

                    b.HasOne("URegister.Core.Data.Models.Process.Process", "FromProcess")
                        .WithMany("ChangeProcesses")
                        .HasForeignKey("FromProcessId")
                        .HasConstraintName("fk_processes_processes_from_process_id");

                    b.HasOne("URegister.Core.Data.Models.Common.ServiceStep", "LastServiceStep")
                        .WithMany("Processes")
                        .HasForeignKey("LastServiceStepId")
                        .HasConstraintName("fk_processes_service_steps_last_service_step_id");

                    b.HasOne("URegister.Core.Data.Models.Common.Service", "Service")
                        .WithMany()
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_processes_services_service_id");

                    b.Navigation("Form");

                    b.Navigation("FromProcess");

                    b.Navigation("LastServiceStep");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("URegister.Core.Data.Models.Process.ProcessStep", b =>
                {
                    b.HasOne("URegister.Core.Data.Models.Process.Process", "Process")
                        .WithMany("ProcessSteps")
                        .HasForeignKey("ProcessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_process_steps_processes_process_id");

                    b.HasOne("URegister.Core.Data.Models.Common.ServiceStep", "ServiceStep")
                        .WithMany()
                        .HasForeignKey("ServiceStepId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_process_steps_service_steps_service_step_id");

                    b.Navigation("Process");

                    b.Navigation("ServiceStep");
                });

            modelBuilder.Entity("URegister.Core.Data.Models.Process.RegisterItem", b =>
                {
                    b.HasOne("URegister.Core.Data.Models.Process.Process", "Process")
                        .WithMany("RegisterItems")
                        .HasForeignKey("ProcessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_register_items_processes_process_id");

                    b.HasOne("URegister.Core.Data.Models.Process.ProcessStep", "ProcessStep")
                        .WithMany()
                        .HasForeignKey("ProcessStepId")
                        .HasConstraintName("fk_register_items_process_steps_process_step_id");

                    b.Navigation("Process");

                    b.Navigation("ProcessStep");
                });

            modelBuilder.Entity("URegister.Infrastructure.Data.AuditLog.AuditEntity", b =>
                {
                    b.HasOne("URegister.Infrastructure.Data.AuditLog.Audit", "Audit")
                        .WithMany("AuditEntities")
                        .HasForeignKey("AuditId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_audit_entity_audits_audit_id");

                    b.Navigation("Audit");
                });

            modelBuilder.Entity("RulesEngine.Models.Rule", b =>
                {
                    b.Navigation("LocalParams");

                    b.Navigation("Rules");
                });

            modelBuilder.Entity("RulesEngine.Models.Workflow", b =>
                {
                    b.Navigation("GlobalParams");

                    b.Navigation("Rules");
                });

            modelBuilder.Entity("URegister.Core.Data.Models.Common.Service", b =>
                {
                    b.Navigation("ServiceSteps");
                });

            modelBuilder.Entity("URegister.Core.Data.Models.Common.ServiceStep", b =>
                {
                    b.Navigation("Processes");

                    b.Navigation("StepRoles");
                });

            modelBuilder.Entity("URegister.Core.Data.Models.Process.Instruction", b =>
                {
                    b.Navigation("InstructionResponses");
                });

            modelBuilder.Entity("URegister.Core.Data.Models.Process.Process", b =>
                {
                    b.Navigation("ChangeProcesses");

                    b.Navigation("Instructions");

                    b.Navigation("ProcessDeliveries");

                    b.Navigation("ProcessSteps");

                    b.Navigation("RegisterItems");
                });

            modelBuilder.Entity("URegister.Infrastructure.Data.AuditLog.Audit", b =>
                {
                    b.Navigation("AuditEntities");
                });
#pragma warning restore 612, 618
        }
    }
}
