// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using URegister.IntegrationsCatalog.Data;

#nullable disable

namespace URegister.IntegrationsCatalog.Migrations
{
    [DbContext(typeof(IntegrationsCatalogDbContext))]
    [Migration("20251125163028_EdeliveryMessageRetry")]
    partial class EdeliveryMessageRetry
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RulesEngine.Models.Rule", b =>
                {
                    b.Property<string>("RuleName")
                        .HasColumnType("text")
                        .HasColumnName("rule_name");

                    b.Property<string>("Actions")
                        .HasColumnType("text")
                        .HasColumnName("actions");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean")
                        .HasColumnName("enabled");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<string>("Expression")
                        .HasColumnType("text")
                        .HasColumnName("expression");

                    b.Property<string>("Operator")
                        .HasColumnType("text")
                        .HasColumnName("operator");

                    b.Property<string>("Properties")
                        .HasColumnType("text")
                        .HasColumnName("properties");

                    b.Property<int>("RuleExpressionType")
                        .HasColumnType("integer")
                        .HasColumnName("rule_expression_type");

                    b.Property<string>("RuleNameFK")
                        .HasColumnType("text")
                        .HasColumnName("rule_name_fk");

                    b.Property<string>("SuccessEvent")
                        .HasColumnType("text")
                        .HasColumnName("success_event");

                    b.Property<string>("WorkflowName")
                        .HasColumnType("text")
                        .HasColumnName("workflow_name");

                    b.HasKey("RuleName")
                        .HasName("pk_rules");

                    b.HasIndex("RuleNameFK")
                        .HasDatabaseName("ix_rules_rule_name_fk");

                    b.HasIndex("WorkflowName")
                        .HasDatabaseName("ix_rules_workflow_name");

                    b.ToTable("rules", (string)null);
                });

            modelBuilder.Entity("RulesEngine.Models.ScopedParam", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Expression")
                        .HasColumnType("text")
                        .HasColumnName("expression");

                    b.Property<string>("RuleName")
                        .HasColumnType("text")
                        .HasColumnName("rule_name");

                    b.Property<string>("WorkflowName")
                        .HasColumnType("text")
                        .HasColumnName("workflow_name");

                    b.HasKey("Name")
                        .HasName("pk_scoped_param");

                    b.HasIndex("RuleName")
                        .HasDatabaseName("ix_scoped_param_rule_name");

                    b.HasIndex("WorkflowName")
                        .HasDatabaseName("ix_scoped_param_workflow_name");

                    b.ToTable("scoped_param", (string)null);
                });

            modelBuilder.Entity("RulesEngine.Models.Workflow", b =>
                {
                    b.Property<string>("WorkflowName")
                        .HasColumnType("text")
                        .HasColumnName("workflow_name");

                    b.Property<int>("RuleExpressionType")
                        .HasColumnType("integer")
                        .HasColumnName("rule_expression_type");

                    b.HasKey("WorkflowName")
                        .HasName("pk_workflows");

                    b.ToTable("workflows", (string)null);
                });

            modelBuilder.Entity("URegister.IntegrationsCatalog.Data.Models.EDeliveryFileMetadata", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasComment("Идентификатор");

                    b.Property<int>("BlobId")
                        .HasColumnType("integer")
                        .HasColumnName("blob_id")
                        .HasComment("Идентификатор на файл от  съобщение");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("timestamptz")
                        .HasColumnName("deleted_on")
                        .HasComment("Дата на изтриване");

                    b.Property<Guid>("EDeliveryMessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("e_delivery_message_id")
                        .HasComment("Идентификатор на съобщение");

                    b.Property<Guid?>("FileId")
                        .HasColumnType("uuid")
                        .HasColumnName("file_id")
                        .HasComment("Идентификатор на файла в хранилището");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("file_name")
                        .HasComment("Име на файла");

                    b.Property<int>("FileSourceTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("file_source_type_id")
                        .HasComment("Идентификатор на роля на файла");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active")
                        .HasComment("Дали записът е активен");

                    b.Property<Guid>("ModifiedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("modified_by_user_id")
                        .HasComment("Идентификатор на потребителят променил последно записа");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("timestamptz")
                        .HasColumnName("modified_on")
                        .HasComment("Дата на последна промяна");

                    b.Property<string>("Rnu")
                        .HasColumnType("text")
                        .HasColumnName("rnu")
                        .HasComment("Референтен номер на услуга (РНУ)");

                    b.HasKey("Id")
                        .HasName("pk_e_delivery_file_metadata");

                    b.HasIndex("EDeliveryMessageId")
                        .HasDatabaseName("ix_e_delivery_file_metadata_e_delivery_message_id");

                    b.ToTable("e_delivery_file_metadata", null, t =>
                        {
                            t.HasComment("Инфорация за качен от потребител файл");
                        });
                });

            modelBuilder.Entity("URegister.IntegrationsCatalog.Data.Models.EDeliveryMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasComment("Идентификатор");

                    b.Property<string>("AdministrationUic")
                        .HasColumnType("text")
                        .HasColumnName("administration_uic")
                        .HasComment("Идентификатор на администрация");

                    b.Property<string>("ApplicationJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("application_json")
                        .HasComment("Информация от пдф");

                    b.Property<string>("ApplicationSubmission")
                        .HasColumnType("jsonb")
                        .HasColumnName("application_submission")
                        .HasComment("Информация от пдф json_submission");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("timestamptz")
                        .HasColumnName("deleted_on")
                        .HasComment("Дата на изтриване");

                    b.Property<int>("ErrorCountSend")
                        .HasColumnType("integer")
                        .HasColumnName("error_count_send")
                        .HasComment("Брой повторения при грешно изпращане");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message")
                        .HasComment("Грешка");

                    b.Property<DateTime?>("IncomingDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("incoming_date")
                        .HasComment("Входяща дата на заявена услуга");

                    b.Property<string>("IncomingNumber")
                        .HasColumnType("text")
                        .HasColumnName("incoming_number")
                        .HasComment("Входящ номер на заявена услуга");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active")
                        .HasComment("Дали записът е активен");

                    b.Property<string>("Message")
                        .HasColumnType("jsonb")
                        .HasColumnName("message")
                        .HasComment("Информация от съобщението при open");

                    b.Property<int>("MessageId")
                        .HasColumnType("integer")
                        .HasColumnName("message_id")
                        .HasComment("Идентификатор на съобщение");

                    b.Property<string>("MessageText")
                        .HasColumnType("text")
                        .HasColumnName("message_text")
                        .HasComment("Текст на съобщението при изпращане");

                    b.Property<int>("MessageTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("message_type_id")
                        .HasComment("Вид съобщение");

                    b.Property<Guid>("ModifiedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("modified_by_user_id")
                        .HasComment("Идентификатор на потребителят променил последно записа");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("timestamptz")
                        .HasColumnName("modified_on")
                        .HasComment("Дата на последна промяна");

                    b.Property<Guid?>("OutboxId")
                        .HasColumnType("uuid")
                        .HasColumnName("outbox_id")
                        .HasComment("Идентификатор на изходящо съобщение");

                    b.Property<Guid?>("ProcessId")
                        .HasColumnType("uuid")
                        .HasColumnName("process_id")
                        .HasComment("Идентификатор на заявена услуга, по-която е качен файла");

                    b.Property<int?>("RegisterId")
                        .HasColumnType("integer")
                        .HasColumnName("register_id")
                        .HasComment("Идентификатор на регистър");

                    b.Property<string>("Rnu")
                        .HasColumnType("text")
                        .HasColumnName("rnu")
                        .HasComment("Референтен номер на услуга (РНУ)");

                    b.Property<int?>("ServiceId")
                        .HasColumnType("integer")
                        .HasColumnName("service_id")
                        .HasComment("Идентификатор на услуга");

                    b.Property<Guid?>("SourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_id")
                        .HasComment("Идентификатор на връзка");

                    b.Property<int>("SourceType")
                        .HasColumnType("integer")
                        .HasColumnName("source_type")
                        .HasComment("Вид връзка");

                    b.Property<int>("StatusId")
                        .HasColumnType("integer")
                        .HasColumnName("status_id")
                        .HasComment("Статус");

                    b.Property<int>("StepId")
                        .HasColumnType("integer")
                        .HasColumnName("step_id")
                        .HasComment("Стъпка");

                    b.Property<string>("SubjectText")
                        .HasColumnType("text")
                        .HasColumnName("subject_text")
                        .HasComment("Subject на съобщението при изпращане");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id")
                        .HasComment("Идентификатор на администрация");

                    b.HasKey("Id")
                        .HasName("pk_e_delivery_messages");

                    b.ToTable("e_delivery_messages", (string)null);
                });

            modelBuilder.Entity("URegister.IntegrationsCatalog.Data.Models.EMailMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasComment("Идентификатор");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("timestamptz")
                        .HasColumnName("deleted_on")
                        .HasComment("Дата на изтриване");

                    b.Property<string>("EMail")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("e_mail")
                        .HasComment("е-маил адрес");

                    b.Property<int>("ErrorCount")
                        .HasColumnType("integer")
                        .HasColumnName("error_count")
                        .HasComment("Брой грешки");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message")
                        .HasComment("Грешка");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active")
                        .HasComment("Дали записът е активен");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message")
                        .HasComment("Съобщение");

                    b.Property<Guid>("ModifiedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("modified_by_user_id")
                        .HasComment("Идентификатор на потребителят променил последно записа");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("timestamptz")
                        .HasColumnName("modified_on")
                        .HasComment("Дата на последна промяна");

                    b.Property<string>("PersonName")
                        .HasColumnType("text")
                        .HasColumnName("person_name")
                        .HasComment("Получател");

                    b.Property<Guid?>("SourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_id")
                        .HasComment("Идентификатор на връзка");

                    b.Property<int>("SourceType")
                        .HasColumnType("integer")
                        .HasColumnName("source_type")
                        .HasComment("Вид връзка");

                    b.Property<int>("StatusId")
                        .HasColumnType("integer")
                        .HasColumnName("status_id")
                        .HasComment("Статус");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("subject");

                    b.HasKey("Id")
                        .HasName("pk_e_mail_messages");

                    b.ToTable("e_mail_messages", (string)null);
                });

            modelBuilder.Entity("RulesEngine.Models.Rule", b =>
                {
                    b.HasOne("RulesEngine.Models.Rule", null)
                        .WithMany("Rules")
                        .HasForeignKey("RuleNameFK")
                        .HasConstraintName("fk_rules_rules_rule_name_fk");

                    b.HasOne("RulesEngine.Models.Workflow", null)
                        .WithMany("Rules")
                        .HasForeignKey("WorkflowName")
                        .HasConstraintName("fk_rules_workflows_workflow_name");
                });

            modelBuilder.Entity("RulesEngine.Models.ScopedParam", b =>
                {
                    b.HasOne("RulesEngine.Models.Rule", null)
                        .WithMany("LocalParams")
                        .HasForeignKey("RuleName")
                        .HasConstraintName("fk_scoped_param_rules_rule_name");

                    b.HasOne("RulesEngine.Models.Workflow", null)
                        .WithMany("GlobalParams")
                        .HasForeignKey("WorkflowName")
                        .HasConstraintName("fk_scoped_param_workflows_workflow_name");
                });

            modelBuilder.Entity("URegister.IntegrationsCatalog.Data.Models.EDeliveryFileMetadata", b =>
                {
                    b.HasOne("URegister.IntegrationsCatalog.Data.Models.EDeliveryMessage", "EDeliveryMessage")
                        .WithMany("EDeliveryFiles")
                        .HasForeignKey("EDeliveryMessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_e_delivery_file_metadata_e_delivery_messages_e_delivery_mes");

                    b.Navigation("EDeliveryMessage");
                });

            modelBuilder.Entity("RulesEngine.Models.Rule", b =>
                {
                    b.Navigation("LocalParams");

                    b.Navigation("Rules");
                });

            modelBuilder.Entity("RulesEngine.Models.Workflow", b =>
                {
                    b.Navigation("GlobalParams");

                    b.Navigation("Rules");
                });

            modelBuilder.Entity("URegister.IntegrationsCatalog.Data.Models.EDeliveryMessage", b =>
                {
                    b.Navigation("EDeliveryFiles");
                });
#pragma warning restore 612, 618
        }
    }
}
