<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Extensions\**" />
    <EmbeddedResource Remove="Extensions\**" />
    <None Remove="Extensions\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="EPPlus" Version="8.1.0" />
    <PackageReference Include="Grpc.AspNetCore" Version="2.71.0" />
    <PackageReference Include="IO.SignTools" Version="8.0.5" />
    <PackageReference Include="Microsoft.AspNetCore.Http.Features" Version="3.1.32" />
    <PackageReference Include="ncalc" Version="1.3.8" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="PeterO.Cbor" Version="4.5.5" />
    <PackageReference Include="System.Linq.Dynamic.Core" Version="1.6.7" />
    <PackageReference Include="System.Net.Http" Version="4.3.4" />
    <PackageReference Include="System.Text.Encodings.Web" Version="9.0.8" />
    <PackageReference Include="System.Text.Json" Version="9.0.8" />
    <PackageReference Include="System.Text.RegularExpressions" Version="4.3.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\URegister.Infrastructure\URegister.Infrastructure.csproj" />
  </ItemGroup>
	<ItemGroup>
		<Protobuf Include="..\protos\nomenclature.proto" GrpcServices="Client" />
		<Protobuf Include="..\protos\object.proto" GrpcServices="Client" />
		<Protobuf Include="..\protos\register.proto" GrpcServices="Client" />
		<Protobuf Include="..\protos\number.proto" GrpcServices="Client" />
		<Protobuf Include="..\protos\integration.proto" GrpcServices="Client" />
		<Protobuf Include="..\protos\user.proto" GrpcServices="Client" />
	</ItemGroup>
</Project>
