// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using URegister.RegistersCatalog.Data;

#nullable disable

namespace URegister.RegistersCatalog.Migrations
{
    [DbContext(typeof(RegistersCatalogDbContext))]
    [Migration("20251208062524_EFormServiceType")]
    partial class EFormServiceType
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RulesEngine.Models.Rule", b =>
                {
                    b.Property<string>("RuleName")
                        .HasColumnType("text")
                        .HasColumnName("rule_name");

                    b.Property<string>("Actions")
                        .HasColumnType("text")
                        .HasColumnName("actions");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean")
                        .HasColumnName("enabled");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<string>("Expression")
                        .HasColumnType("text")
                        .HasColumnName("expression");

                    b.Property<string>("Operator")
                        .HasColumnType("text")
                        .HasColumnName("operator");

                    b.Property<string>("Properties")
                        .HasColumnType("text")
                        .HasColumnName("properties");

                    b.Property<int>("RuleExpressionType")
                        .HasColumnType("integer")
                        .HasColumnName("rule_expression_type");

                    b.Property<string>("RuleNameFK")
                        .HasColumnType("text")
                        .HasColumnName("rule_name_fk");

                    b.Property<string>("SuccessEvent")
                        .HasColumnType("text")
                        .HasColumnName("success_event");

                    b.Property<string>("WorkflowName")
                        .HasColumnType("text")
                        .HasColumnName("workflow_name");

                    b.HasKey("RuleName")
                        .HasName("pk_rules");

                    b.HasIndex("RuleNameFK")
                        .HasDatabaseName("ix_rules_rule_name_fk");

                    b.HasIndex("WorkflowName")
                        .HasDatabaseName("ix_rules_workflow_name");

                    b.ToTable("rules", (string)null);
                });

            modelBuilder.Entity("RulesEngine.Models.ScopedParam", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Expression")
                        .HasColumnType("text")
                        .HasColumnName("expression");

                    b.Property<string>("RuleName")
                        .HasColumnType("text")
                        .HasColumnName("rule_name");

                    b.Property<string>("WorkflowName")
                        .HasColumnType("text")
                        .HasColumnName("workflow_name");

                    b.HasKey("Name")
                        .HasName("pk_scoped_param");

                    b.HasIndex("RuleName")
                        .HasDatabaseName("ix_scoped_param_rule_name");

                    b.HasIndex("WorkflowName")
                        .HasDatabaseName("ix_scoped_param_workflow_name");

                    b.ToTable("scoped_param", (string)null);
                });

            modelBuilder.Entity("RulesEngine.Models.Workflow", b =>
                {
                    b.Property<string>("WorkflowName")
                        .HasColumnType("text")
                        .HasColumnName("workflow_name");

                    b.Property<int>("RuleExpressionType")
                        .HasColumnType("integer")
                        .HasColumnName("rule_expression_type");

                    b.HasKey("WorkflowName")
                        .HasName("pk_workflows");

                    b.ToTable("workflows", (string)null);
                });

            modelBuilder.Entity("URegister.RegistersCatalog.Data.Models.Administration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasComment("Идентификатор");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on")
                        .HasComment("Дата на създаване");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("timestamptz")
                        .HasColumnName("deleted_on")
                        .HasComment("Дата на изтриване");

                    b.Property<string>("EFormCode")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("e_form_code")
                        .HasComment("Код за връзка с е-форми");

                    b.Property<int>("FrequencyId")
                        .HasColumnType("integer")
                        .HasColumnName("frequency_id")
                        .HasComment("Автоматично изпращане на данни към OpenData 1 ежедневно 2 седмично 3 месечно");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active")
                        .HasComment("Дали записът е активен");

                    b.Property<Guid>("ModifiedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("modified_by_user_id")
                        .HasComment("Идентификатор на потребителят променил последно записа");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("timestamptz")
                        .HasColumnName("modified_on")
                        .HasComment("Дата на последна промяна");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("name")
                        .HasComment("Име");

                    b.Property<string>("NameEDelivery")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name_e_delivery")
                        .HasComment("Съкратено име на администрация ползва се при пращане на съобщение към ССЕВ");

                    b.Property<string>("OpenDataApiKey")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("open_data_api_key")
                        .HasComment("api-key за opendata");

                    b.Property<int>("OpenDataOrgId")
                        .HasColumnType("integer")
                        .HasColumnName("open_data_org_id")
                        .HasComment("Идентификатор на организация в  opendata");

                    b.Property<string>("Uic")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("uic")
                        .HasComment("ЕИК");

                    b.HasKey("Id")
                        .HasName("pk_administration");

                    b.HasIndex("Uic")
                        .IsUnique()
                        .HasDatabaseName("ix_administration_uic");

                    b.ToTable("administration", null, t =>
                        {
                            t.HasComment("Администрации");
                        });
                });

            modelBuilder.Entity("URegister.RegistersCatalog.Data.Models.AdministrationPerson", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasComment("Идентификатор");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid>("AdministrationId")
                        .HasColumnType("uuid")
                        .HasColumnName("administration_id")
                        .HasComment("Идентификатор на администрация");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on")
                        .HasComment("Дата на създаване");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("timestamptz")
                        .HasColumnName("deleted_on")
                        .HasComment("Дата на изтриване");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("email")
                        .HasComment("Имейл");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("first_name")
                        .HasComment("Име");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active")
                        .HasComment("Дали записът е активен");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("last_name")
                        .HasComment("Фамилия");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("middle_name")
                        .HasComment("Презиме");

                    b.Property<Guid>("ModifiedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("modified_by_user_id")
                        .HasComment("Идентификатор на потребителят променил последно записа");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("timestamptz")
                        .HasColumnName("modified_on")
                        .HasComment("Дата на последна промяна");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone")
                        .HasComment("Телефон");

                    b.Property<string>("Position")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("position")
                        .HasComment("Длъжност");

                    b.Property<int?>("RegisterId")
                        .IsRequired()
                        .HasColumnType("integer")
                        .HasColumnName("register_id")
                        .HasComment("Идентификатор на регистър");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type")
                        .HasComment("Тип лице");

                    b.HasKey("Id")
                        .HasName("pk_administration_person");

                    b.HasIndex("AdministrationId")
                        .HasDatabaseName("ix_administration_person_administration_id");

                    b.HasIndex("RegisterId")
                        .HasDatabaseName("ix_administration_person_register_id");

                    b.ToTable("administration_person", null, t =>
                        {
                            t.HasComment("Лица от администрацията");
                        });
                });

            modelBuilder.Entity("URegister.RegistersCatalog.Data.Models.CalendarDay", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CurrentDate")
                        .HasColumnType("date")
                        .HasColumnName("current_date");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("timestamptz")
                        .HasColumnName("deleted_on")
                        .HasComment("Дата на изтриване");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active")
                        .HasComment("Дали записът е активен");

                    b.Property<string>("KindId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("kind_id");

                    b.Property<Guid>("ModifiedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("modified_by_user_id")
                        .HasComment("Идентификатор на потребителят променил последно записа");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("timestamptz")
                        .HasColumnName("modified_on")
                        .HasComment("Дата на последна промяна");

                    b.HasKey("Id")
                        .HasName("pk_calendar_days");

                    b.ToTable("calendar_days", null, t =>
                        {
                            t.HasComment("Работни дни");
                        });
                });

            modelBuilder.Entity("URegister.RegistersCatalog.Data.Models.MasterPersonRecordsIndex", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasComment("Идентификатор");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on")
                        .HasComment("Дата на създаване");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("timestamptz")
                        .HasColumnName("deleted_on")
                        .HasComment("Дата на изтриване");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active")
                        .HasComment("Дали записът е активен");

                    b.Property<Guid?>("MasterPersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("master_person_id")
                        .HasComment("Идентификатор на основно лице");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("name")
                        .HasComment("Име");

                    b.Property<string>("Pid")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("pid")
                        .HasComment("Идентификатор на лице");

                    b.Property<string>("PidType")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("pid_type")
                        .HasComment("Тип на идентификатора");

                    b.HasKey("Id")
                        .HasName("pk_master_person_records");

                    b.HasIndex("Pid", "PidType")
                        .IsUnique()
                        .HasDatabaseName("ix_master_person_records_pid_pid_type");

                    b.ToTable("master_person_records", null, t =>
                        {
                            t.HasComment("Глобална партида на лице");
                        });
                });

            modelBuilder.Entity("URegister.RegistersCatalog.Data.Models.Register", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasComment("Идентификатор");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AppId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("app_id")
                        .HasComment("AppId за Stampit");

                    b.Property<string>("AppSecret")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("app_secret")
                        .HasComment("AppSecret за Stampit");

                    b.Property<string>("BaseAddress")
                        .HasColumnType("text")
                        .HasColumnName("base_address")
                        .HasComment("Базов адрес");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("code")
                        .HasComment("Код на регистър");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on")
                        .HasComment("Дата на създаване");

                    b.Property<DateTime?>("DateDeploy")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_deploy")
                        .HasComment("Дата на старт на deploy");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("timestamptz")
                        .HasColumnName("deleted_on")
                        .HasComment("Дата на изтриване");

                    b.Property<bool>("Deployed")
                        .HasColumnType("boolean")
                        .HasColumnName("deployed")
                        .HasComment("Стартиран ли е контейнер за регистъра");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description")
                        .HasComment("Описание");

                    b.Property<bool?>("HistoryNotPublic")
                        .HasColumnType("boolean")
                        .HasColumnName("history_not_public")
                        .HasComment("Историята не е публична");

                    b.Property<string>("IdentitySecurityLevel")
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("identity_security_level")
                        .HasComment("Ниво на осигуреност на средствата за електронна идентификация");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active")
                        .HasComment("Дали записът е активен");

                    b.Property<string>("LegalBasis")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("legal_basis")
                        .HasComment("Правно основание");

                    b.Property<Guid>("ModifiedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("modified_by_user_id")
                        .HasComment("Идентификатор на потребителят променил последно записа");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("timestamptz")
                        .HasColumnName("modified_on")
                        .HasComment("Дата на последна промяна");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("name")
                        .HasComment("Име на регистър");

                    b.Property<string>("NameEDelivery")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name_e_delivery")
                        .HasComment("Съкратено име на регистър ползва се при пращане на съобщение към ССЕВ");

                    b.Property<int>("OpenDataCategoryId")
                        .HasColumnType("integer")
                        .HasColumnName("open_data_category_id")
                        .HasComment("Категория opendata");

                    b.Property<string>("OpenDataTags")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("open_data_tags")
                        .HasComment("Тагове opendata");

                    b.Property<DateTime?>("StartedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_on")
                        .HasComment("Дата на стартиране");

                    b.Property<int>("StatusId")
                        .HasColumnType("integer")
                        .HasColumnName("status_id")
                        .HasComment("Идентификатор на статус");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("type")
                        .HasComment("Вид на регистъра");

                    b.Property<string>("TypeEntry")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("type_entry")
                        .HasComment("Начин на вписване");

                    b.HasKey("Id")
                        .HasName("pk_registers");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_registers_code");

                    b.ToTable("registers", null, t =>
                        {
                            t.HasComment("Регистри");
                        });
                });

            modelBuilder.Entity("URegister.RegistersCatalog.Data.Models.RegisterAdministration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasComment("Идентификатор");

                    b.Property<Guid>("AdministrationId")
                        .HasColumnType("uuid")
                        .HasColumnName("administration_id")
                        .HasComment("Идентификатор");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on")
                        .HasComment("Дата на създаване");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("timestamptz")
                        .HasColumnName("deleted_on")
                        .HasComment("Дата на изтриване");

                    b.Property<int>("FrequencyId")
                        .HasColumnType("integer")
                        .HasColumnName("frequency_id")
                        .HasComment("Автоматично изпращане на данни към OpenData 1 ежедневно 2 седмично 3 месечно");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active")
                        .HasComment("Дали записът е активен");

                    b.Property<string>("LegalBasis")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("legal_basis")
                        .HasComment("Правно основание");

                    b.Property<Guid>("ModifiedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("modified_by_user_id")
                        .HasComment("Идентификатор на потребителят променил последно записа");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("timestamptz")
                        .HasColumnName("modified_on")
                        .HasComment("Дата на последна промяна");

                    b.Property<string>("OpenDataDataSetId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("open_data_data_set_id")
                        .HasComment("OpenData DataSetId");

                    b.Property<int>("RegisterId")
                        .HasColumnType("integer")
                        .HasColumnName("register_id")
                        .HasComment("Идентификатор на регистър");

                    b.Property<string>("ResourceMetaId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("resource_meta_id")
                        .HasComment("OpenData ResourceMetaId");

                    b.HasKey("Id")
                        .HasName("pk_register_administrations");

                    b.HasIndex("AdministrationId")
                        .HasDatabaseName("ix_register_administrations_administration_id");

                    b.HasIndex("RegisterId", "AdministrationId")
                        .IsUnique()
                        .HasDatabaseName("ix_register_administrations_register_id_administration_id");

                    b.ToTable("register_administrations", null, t =>
                        {
                            t.HasComment("Администрации");
                        });
                });

            modelBuilder.Entity("URegister.RegistersCatalog.Data.Models.RegisterFileMetadata", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasComment("Идентификатор");

                    b.Property<string>("CodeableConceptCode")
                        .HasColumnType("text")
                        .HasColumnName("codeable_concept_code")
                        .HasComment("Тип файл");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("timestamptz")
                        .HasColumnName("deleted_on")
                        .HasComment("Дата на изтриване");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description")
                        .HasComment("Описание");

                    b.Property<Guid>("FileId")
                        .HasColumnType("uuid")
                        .HasColumnName("file_id")
                        .HasComment("Идентификатор на файла в хранилището");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("file_name")
                        .HasComment("Име на файла");

                    b.Property<int>("FileSourceTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("file_source_type_id")
                        .HasComment("Идентификатор на роля на файла");

                    b.Property<string>("Hash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("hash")
                        .HasComment("Хеш сума");

                    b.Property<string>("HashingAlgorithm")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("hashing_algorithm")
                        .HasComment("Алгоритъм за изчисляване на хеш сума");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active")
                        .HasComment("Дали записът е активен");

                    b.Property<Guid>("ModifiedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("modified_by_user_id")
                        .HasComment("Идентификатор на потребителят променил последно записа");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("timestamptz")
                        .HasColumnName("modified_on")
                        .HasComment("Дата на последна промяна");

                    b.Property<string>("NomenclatureType")
                        .HasColumnType("text")
                        .HasColumnName("nomenclature_type")
                        .HasComment("Type of NomenclatureType");

                    b.Property<int?>("RegisterId")
                        .HasColumnType("integer")
                        .HasColumnName("register_id");

                    b.Property<string>("Signature")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("signature")
                        .HasComment("Подпис");

                    b.Property<string>("SourceId")
                        .HasColumnType("text")
                        .HasColumnName("source_id")
                        .HasComment("Идентификатор на сорс");

                    b.HasKey("Id")
                        .HasName("pk_register_file_metadata");

                    b.ToTable("register_file_metadata", null, t =>
                        {
                            t.HasComment("Инфорация за качен от потребител файл");
                        });
                });

            modelBuilder.Entity("URegister.RegistersCatalog.Data.Models.RegisterPersonRecord", b =>
                {
                    b.Property<int>("RegisterId")
                        .HasColumnType("integer")
                        .HasColumnName("register_id")
                        .HasComment("Идентификатор на регистър");

                    b.Property<Guid>("MasterPersonRecordId")
                        .HasColumnType("uuid")
                        .HasColumnName("master_person_record_id")
                        .HasComment("Идентификатор на партида");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("role_id")
                        .HasComment("Роля партида/заявител");

                    b.HasKey("RegisterId", "MasterPersonRecordId", "RoleId")
                        .HasName("pk_register_person_records");

                    b.HasIndex("MasterPersonRecordId")
                        .HasDatabaseName("ix_register_person_records_master_person_record_id");

                    b.ToTable("register_person_records", null, t =>
                        {
                            t.HasComment("Записи на лица в регистър");
                        });
                });

            modelBuilder.Entity("URegister.RegistersCatalog.Data.Models.RegisterService", b =>
                {
                    b.Property<int>("RegisterId")
                        .HasColumnType("integer")
                        .HasColumnName("register_id")
                        .HasComment("Идентификатор на регистър");

                    b.Property<int>("ServiceId")
                        .HasColumnType("integer")
                        .HasColumnName("service_id")
                        .HasComment("Идентификатор на услуга");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("timestamptz")
                        .HasColumnName("deleted_on")
                        .HasComment("Дата на изтриване");

                    b.Property<string>("EFormCode")
                        .HasColumnType("text")
                        .HasColumnName("e_form_code")
                        .HasComment("Референтен номер на услуга (РНУ)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active")
                        .HasComment("Дали записът е активен");

                    b.Property<Guid>("ModifiedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("modified_by_user_id")
                        .HasComment("Идентификатор на потребителят променил последно записа");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("timestamptz")
                        .HasColumnName("modified_on")
                        .HasComment("Дата на последна промяна");

                    b.Property<int>("ServiceTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("service_type_id")
                        .HasComment("Идентификатор на услуга");

                    b.HasKey("RegisterId", "ServiceId")
                        .HasName("pk_register_services");

                    b.ToTable("register_services", null, t =>
                        {
                            t.HasComment("Услуга в регистъра");
                        });
                });

            modelBuilder.Entity("URegister.RegistersCatalog.Data.Models.RegisterStatus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasComment("Идентификатор");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("timestamptz")
                        .HasColumnName("deleted_on")
                        .HasComment("Дата на изтриване");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active")
                        .HasComment("Дали записът е активен");

                    b.Property<Guid>("ModifiedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("modified_by_user_id")
                        .HasComment("Идентификатор на потребителят променил последно записа");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("timestamptz")
                        .HasColumnName("modified_on")
                        .HasComment("Дата на последна промяна");

                    b.Property<int>("RegisterId")
                        .HasColumnType("integer")
                        .HasColumnName("register_id")
                        .HasComment("Идентификатор на регистър");

                    b.Property<string>("Remark")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("remark")
                        .HasComment("Забележка");

                    b.Property<int>("StatusId")
                        .HasColumnType("integer")
                        .HasColumnName("status_id")
                        .HasComment("Идентификатор на статус");

                    b.HasKey("Id")
                        .HasName("pk_register_status");

                    b.HasIndex("RegisterId")
                        .HasDatabaseName("ix_register_status_register_id");

                    b.ToTable("register_status", null, t =>
                        {
                            t.HasComment("Статуси на регистър");
                        });
                });

            modelBuilder.Entity("RulesEngine.Models.Rule", b =>
                {
                    b.HasOne("RulesEngine.Models.Rule", null)
                        .WithMany("Rules")
                        .HasForeignKey("RuleNameFK")
                        .HasConstraintName("fk_rules_rules_rule_name_fk");

                    b.HasOne("RulesEngine.Models.Workflow", null)
                        .WithMany("Rules")
                        .HasForeignKey("WorkflowName")
                        .HasConstraintName("fk_rules_workflows_workflow_name");
                });

            modelBuilder.Entity("RulesEngine.Models.ScopedParam", b =>
                {
                    b.HasOne("RulesEngine.Models.Rule", null)
                        .WithMany("LocalParams")
                        .HasForeignKey("RuleName")
                        .HasConstraintName("fk_scoped_param_rules_rule_name");

                    b.HasOne("RulesEngine.Models.Workflow", null)
                        .WithMany("GlobalParams")
                        .HasForeignKey("WorkflowName")
                        .HasConstraintName("fk_scoped_param_workflows_workflow_name");
                });

            modelBuilder.Entity("URegister.RegistersCatalog.Data.Models.AdministrationPerson", b =>
                {
                    b.HasOne("URegister.RegistersCatalog.Data.Models.Administration", "Administration")
                        .WithMany("People")
                        .HasForeignKey("AdministrationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_administration_person_administration_administration_id");

                    b.HasOne("URegister.RegistersCatalog.Data.Models.Register", "Register")
                        .WithMany()
                        .HasForeignKey("RegisterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_administration_person_registers_register_id");

                    b.Navigation("Administration");

                    b.Navigation("Register");
                });

            modelBuilder.Entity("URegister.RegistersCatalog.Data.Models.RegisterAdministration", b =>
                {
                    b.HasOne("URegister.RegistersCatalog.Data.Models.Administration", "Administration")
                        .WithMany("RegisterAdministrations")
                        .HasForeignKey("AdministrationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_register_administrations_administration_administration_id");

                    b.HasOne("URegister.RegistersCatalog.Data.Models.Register", "Register")
                        .WithMany("RegisterAdministrations")
                        .HasForeignKey("RegisterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_register_administrations_registers_register_id");

                    b.Navigation("Administration");

                    b.Navigation("Register");
                });

            modelBuilder.Entity("URegister.RegistersCatalog.Data.Models.RegisterPersonRecord", b =>
                {
                    b.HasOne("URegister.RegistersCatalog.Data.Models.MasterPersonRecordsIndex", "MasterPersonRecord")
                        .WithMany("RegisterPersonRecords")
                        .HasForeignKey("MasterPersonRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_register_person_records_master_person_records_master_person");

                    b.HasOne("URegister.RegistersCatalog.Data.Models.Register", "Register")
                        .WithMany()
                        .HasForeignKey("RegisterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_register_person_records_registers_register_id");

                    b.Navigation("MasterPersonRecord");

                    b.Navigation("Register");
                });

            modelBuilder.Entity("URegister.RegistersCatalog.Data.Models.RegisterService", b =>
                {
                    b.HasOne("URegister.RegistersCatalog.Data.Models.Register", "Register")
                        .WithMany()
                        .HasForeignKey("RegisterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_register_services_registers_register_id");

                    b.Navigation("Register");
                });

            modelBuilder.Entity("URegister.RegistersCatalog.Data.Models.RegisterStatus", b =>
                {
                    b.HasOne("URegister.RegistersCatalog.Data.Models.Register", "Register")
                        .WithMany()
                        .HasForeignKey("RegisterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_register_status_registers_register_id");

                    b.Navigation("Register");
                });

            modelBuilder.Entity("RulesEngine.Models.Rule", b =>
                {
                    b.Navigation("LocalParams");

                    b.Navigation("Rules");
                });

            modelBuilder.Entity("RulesEngine.Models.Workflow", b =>
                {
                    b.Navigation("GlobalParams");

                    b.Navigation("Rules");
                });

            modelBuilder.Entity("URegister.RegistersCatalog.Data.Models.Administration", b =>
                {
                    b.Navigation("People");

                    b.Navigation("RegisterAdministrations");
                });

            modelBuilder.Entity("URegister.RegistersCatalog.Data.Models.MasterPersonRecordsIndex", b =>
                {
                    b.Navigation("RegisterPersonRecords");
                });

            modelBuilder.Entity("URegister.RegistersCatalog.Data.Models.Register", b =>
                {
                    b.Navigation("RegisterAdministrations");
                });
#pragma warning restore 612, 618
        }
    }
}
