syntax = "proto3";
import "common.proto";
import "google/protobuf/empty.proto";
import "google/protobuf/wrappers.proto";

option csharp_namespace = "URegister.ObjectsCatalog";

package object;

service ObjectsCatalogGrpc {
  rpc GetFieldsList(google.protobuf.Empty) returns (CatalogFieldsListReply);
  rpc GetField(CatalogFieldRequest) returns (CatalogGetFieldReply);
  rpc SetField(CatalogSerializedData) returns (CatalogSetFieldReply);
  rpc SetFieldType(CatalogFieldType) returns (common.ResultStatus);
  rpc GetServiceTypes(common.DatatableRequest) returns (ServiceTypesListReply);
  rpc GetServiceType(GetServiceTypeRequest) returns (GetServiceTypeReply);
  rpc AppendUpdate(ServiceTypeMessage) returns (common.ResultStatus);
  rpc GetStepList(common.DatatableRequest) returns (StepListReply);
  rpc GetStep(GetStepMessage) returns (GetStepReply);
  rpc AppendUpdateStep(StepMessage) returns (common.ResultStatus);
  rpc DeleteServiceType(GetServiceTypeRequest) returns (common.ResultStatus);
  rpc DeleteFieldType(GetFieldTypeRequest) returns (common.ResultStatus);
  rpc CheckServiceTypeNameExists(ServiceTypeNameExistsRequest) returns (ServiceTypeNameExistsReply);
  rpc DeleteStep(GetStepMessage) returns (common.ResultStatus);
  rpc GetFieldTemplateList(FieldTemplateListRequest) returns (FieldTemplateListResponse);
  rpc GetFieldTemplate(FieldTemplateRequest) returns (FieldTemplateResponse);
  rpc GetFieldTemplateContent(FieldTemplateRequest) returns (FieldTemplateContentResponse);
  rpc GetFieldTemplateContentList(google.protobuf.Empty) returns (FieldTemplateContentListResponse);
  rpc AppendUpdateFieldTemplate(FieldTemplateMessage) returns (common.ResultStatus);
  rpc UpdateFieldTemplateContent(FieldTemplateContentMessage) returns (common.ResultStatus);
  rpc DeleteFieldTemplate(FieldTemplateRequest) returns (common.ResultStatus);
}

// Тип на поле от каталога
message CatalogFieldType {
  string type = 1;
  string label = 2;
  bool isComplex = 3;
  string templateName = 4;
  int32 field_type_id = 5;
}

// Списък от полета дефинирани в каталога
message CatalogFieldsListReply {
  common.ResultStatus status = 1;
  repeated CatalogFieldType field_types = 2;
}

// Поле от каталога
message CatalogFieldRequest {
  string field_type = 1;
}

// Сериализирани данни за обект от каталога
message CatalogSerializedData {
  string data = 1;
  optional string assembly_qualified_name = 2;
}

// Отговор за искане за поле от каталога
message CatalogGetFieldReply {
  common.ResultStatus status = 1;
  string data = 2;
}

// Отговор за запис на поле от каталога
message CatalogSetFieldReply {
  common.ResultStatus status = 1;
  int32 version = 2;
}

message ServiceTypeMessage {
	int32 id = 1;
	string name = 2;
	repeated int32 step_ids = 3;
}

message GetServiceTypeMessage {
	int32 id = 1;
	string name = 2;
	repeated common.CheckListItem steps = 3;
}

message GetServiceTypeReply {
    common.ResultStatus status = 1;
	GetServiceTypeMessage service_type = 2;
}

message ServiceTypesListReply {
  common.ResultStatus status = 1;
  repeated ServiceTypeMessage service_types = 2;
  int32 count_all = 3;
}

message GetServiceTypeRequest{
	int32 service_id = 1;
}

message GetStepMessage{
    int32 step_id = 1;
} 

message StepMessage{
	int32 id = 1;
	string name = 2;
	google.protobuf.StringValue role_id = 3;
	google.protobuf.StringValue type = 4;
	google.protobuf.StringValue method = 5;
	google.protobuf.StringValue configuration = 6;
	bool is_for_public_use = 7;
	bool is_for_official_use = 8;
	google.protobuf.StringValue role_name = 9;
}

message GetStepReply{
	common.ResultStatus status = 1;
	StepMessage step = 2;
}
message StepListReply{
    common.ResultStatus status = 1;
    repeated StepMessage steps = 2;
	int32 count_all = 3;
}

message GetFieldTypeRequest{
	int32 field_type_id = 1;
}

message ServiceTypeNameExistsRequest
{
	string name = 1;
}

message ServiceTypeNameExistsReply{
	common.ResultStatus status = 1;
	bool is_exists = 2;
}

message FieldTemplateMessage {
	int32 id = 1;
	int32 field_type_id = 2;
	string name = 4;
	google.protobuf.StringValue field_type = 5;
	google.protobuf.StringValue field_type_name = 6;
	bool blank_if_no_value = 7;

}

message FieldTemplateContentMessage {
	int32 id = 1;
	int32 field_type_id = 2;
	string name = 4;
	google.protobuf.StringValue field_type = 5;
	google.protobuf.StringValue field_type_name = 6;
	google.protobuf.StringValue content = 7;
	google.protobuf.StringValue content_text = 8;
	bool blank_if_no_value = 9;

}

message FieldTemplateRequest{
    int32 id = 1;
}

message FieldTemplateListRequest {
	common.DatatableRequest data_table_request = 1;
}

message FieldTemplateListResponse {
    common.ResultStatus status = 1;
    repeated FieldTemplateMessage field_templates = 2;
	int32 count_all = 3;
}
message FieldTemplateContentListResponse {
    common.ResultStatus status = 1;
    repeated FieldTemplateContentMessage field_templates = 2;
}

message FieldTemplateResponse {
    common.ResultStatus status = 1;
    FieldTemplateMessage field_template = 2;
}

message FieldTemplateContentResponse {
    common.ResultStatus status = 1;
    FieldTemplateContentMessage field_template = 2;
}