//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v14.3.0.0 (NJsonSchema v11.2.0.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

#nullable enable

#pragma warning disable 108 // Disable "CS0108 '{derivedDto}.ToJson()' hides inherited member '{dtoBase}.ToJson()'. Use the new keyword if hiding was intended."
#pragma warning disable 114 // Disable "CS0114 '{derivedDto}.RaisePropertyChanged(String)' hides inherited member 'dtoBase.RaisePropertyChanged(String)'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword."
#pragma warning disable 472 // Disable "CS0472 The result of the expression is always 'false' since a value of type 'Int32' is never equal to 'null' of type 'Int32?'
#pragma warning disable 612 // Disable "CS0612 '...' is obsolete"
#pragma warning disable 649 // Disable "CS0649 Field is never assigned to, and will always have its default value null"
#pragma warning disable 1573 // Disable "CS1573 Parameter '...' has no matching param tag in the XML comment for ...
#pragma warning disable 1591 // Disable "CS1591 Missing XML comment for publicly visible type or member ..."
#pragma warning disable 8073 // Disable "CS8073 The result of the expression is always 'false' since a value of type 'T' is never equal to 'null' of type 'T?'"
#pragma warning disable 3016 // Disable "CS3016 Arrays as attribute arguments is not CLS-compliant"
#pragma warning disable 8600 // Disable "CS8600 Converting null literal or possible null value to non-nullable type"
#pragma warning disable 8602 // Disable "CS8602 Dereference of a possibly null reference"
#pragma warning disable 8603 // Disable "CS8603 Possible null reference return"
#pragma warning disable 8604 // Disable "CS8604 Possible null reference argument for parameter"
#pragma warning disable 8625 // Disable "CS8625 Cannot convert null literal to non-nullable reference type"
#pragma warning disable 8765 // Disable "CS8765 Nullability of type of parameter doesn't match overridden member (possibly because of nullability attributes)."

namespace EDelivery.Integration.Contracts
{
    using System = global::System;

    [System.CodeDom.Compiler.GeneratedCode("NSwag", "14.3.0.0 (NJsonSchema v11.2.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial interface IBlobsClient
    {
        /// <summary>
        /// Връща списък с файлове в хранилището
        /// </summary>
        /// <param name="dpMiscinfo">Хедър, съдържащ персонален идентификатор</param>
        /// <exception cref="ApiException">A server side error occurred.</exception>
        System.Threading.Tasks.Task<TableResultDOOfBlobDO> ListAsync(string? dpMiscinfo, int? offset, int? limit);

        /// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation.</param>
        /// <summary>
        /// Връща списък с файлове в хранилището
        /// </summary>
        /// <param name="dpMiscinfo">Хедър, съдържащ персонален идентификатор</param>
        /// <exception cref="ApiException">A server side error occurred.</exception>
        System.Threading.Tasks.Task<TableResultDOOfBlobDO> ListAsync(string? dpMiscinfo, int? offset, int? limit, System.Threading.CancellationToken cancellationToken);

        /// <summary>
        /// Връща файл от хранилището
        /// </summary>
        /// <param name="dpMiscinfo">Хедър, съдържащ персонален идентификатор</param>
        /// <exception cref="ApiException">A server side error occurred.</exception>
        System.Threading.Tasks.Task<TableResultDOOfBlobDO> DetailsAsync(string? dpMiscinfo, int blobId);

        /// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation.</param>
        /// <summary>
        /// Връща файл от хранилището
        /// </summary>
        /// <param name="dpMiscinfo">Хедър, съдържащ персонален идентификатор</param>
        /// <exception cref="ApiException">A server side error occurred.</exception>
        System.Threading.Tasks.Task<TableResultDOOfBlobDO> DetailsAsync(string? dpMiscinfo, int blobId, System.Threading.CancellationToken cancellationToken);

        /// <summary>
        /// Изтрива файл от хранилището
        /// </summary>
        /// <param name="dpMiscinfo">Хедър, съдържащ персонален идентификатор</param>
        /// <exception cref="ApiException">A server side error occurred.</exception>
        System.Threading.Tasks.Task<TableResultDOOfBlobDO> DeleteAsync(string? dpMiscinfo, int blobId);

        /// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation.</param>
        /// <summary>
        /// Изтрива файл от хранилището
        /// </summary>
        /// <param name="dpMiscinfo">Хедър, съдържащ персонален идентификатор</param>
        /// <exception cref="ApiException">A server side error occurred.</exception>
        System.Threading.Tasks.Task<TableResultDOOfBlobDO> DeleteAsync(string? dpMiscinfo, int blobId, System.Threading.CancellationToken cancellationToken);

    }

    [System.CodeDom.Compiler.GeneratedCode("NSwag", "14.3.0.0 (NJsonSchema v11.2.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial interface IOboBlobsClient
    {
        /// <summary>
        /// Връща списък с файлове в хранилището от името на профил
        /// </summary>
        /// <param name="dpMiscinfo">Хедър, съдържащ персонален идентификатор</param>
        /// <exception cref="ApiException">A server side error occurred.</exception>
        System.Threading.Tasks.Task<TableResultDOOfBlobDO> ListOnBehalfAsync(string? dpMiscinfo, int? offset, int? limit);

        /// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation.</param>
        /// <summary>
        /// Връща списък с файлове в хранилището от името на профил
        /// </summary>
        /// <param name="dpMiscinfo">Хедър, съдържащ персонален идентификатор</param>
        /// <exception cref="ApiException">A server side error occurred.</exception>
        System.Threading.Tasks.Task<TableResultDOOfBlobDO> ListOnBehalfAsync(string? dpMiscinfo, int? offset, int? limit, System.Threading.CancellationToken cancellationToken);

        /// <summary>
        /// Връща файл от хранилището от името на профил
        /// </summary>
        /// <param name="dpMiscinfo">Хедър, съдържащ персонален идентификатор</param>
        /// <exception cref="ApiException">A server side error occurred.</exception>
        System.Threading.Tasks.Task<TableResultDOOfBlobDO> DetailsOnBehalfAsync(string? dpMiscinfo, int blobId);

        /// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation.</param>
        /// <summary>
        /// Връща файл от хранилището от името на профил
        /// </summary>
        /// <param name="dpMiscinfo">Хедър, съдържащ персонален идентификатор</param>
        /// <exception cref="ApiException">A server side error occurred.</exception>
        System.Threading.Tasks.Task<TableResultDOOfBlobDO> DetailsOnBehalfAsync(string? dpMiscinfo, int blobId, System.Threading.CancellationToken cancellationToken);

        /// <summary>
        /// Изтрива файл от хранилището от името на профил
        /// </summary>
        /// <param name="dpMiscinfo">Хедър, съдържащ персонален идентификатор</param>
        /// <exception cref="ApiException">A server side error occurred.</exception>
        System.Threading.Tasks.Task<TableResultDOOfBlobDO> DeleteOnBehalfAsync(string? dpMiscinfo, int blobId);

        /// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation.</param>
        /// <summary>
        /// Изтрива файл от хранилището от името на профил
        /// </summary>
        /// <param name="dpMiscinfo">Хедър, съдържащ персонален идентификатор</param>
        /// <exception cref="ApiException">A server side error occurred.</exception>
        System.Threading.Tasks.Task<TableResultDOOfBlobDO> DeleteOnBehalfAsync(string? dpMiscinfo, int blobId, System.Threading.CancellationToken cancellationToken);

    }

    [System.CodeDom.Compiler.GeneratedCode("NSwag", "14.3.0.0 (NJsonSchema v11.2.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial interface IMessagesClient
    {
        /// <summary>
        /// Връща списък с получени съобщения
        /// </summary>
        /// <param name="dpMiscinfo">Хедър, съдържащ персонален идентификатор</param>
        /// <exception cref="ApiException">A server side error occurred.</exception>
        System.Threading.Tasks.Task<TableResultDOOfInboxDO> GetInboxAsync(string? dpMiscinfo, int? offset, int? limit);

        /// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation.</param>
        /// <summary>
        /// Връща списък с получени съобщения
        /// </summary>
        /// <param name="dpMiscinfo">Хедър, съдържащ персонален идентификатор</param>
        /// <exception cref="ApiException">A server side error occurred.</exception>
        System.Threading.Tasks.Task<TableResultDOOfInboxDO> GetInboxAsync(string? dpMiscinfo, int? offset, int? limit, System.Threading.CancellationToken cancellationToken);

        /// <summary>
        /// Връща списък с изпратени съобщения
        /// </summary>
        /// <param name="dpMiscinfo">Хедър, съдържащ персонален идентификатор</param>
        /// <exception cref="ApiException">A server side error occurred.</exception>
        System.Threading.Tasks.Task<TableResultDOOfOutboxDO> GetOutboxAsync(string? dpMiscinfo, int? offset, int? limit);

        /// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation.</param>
        /// <summary>
        /// Връща списък с изпратени съобщения
        /// </summary>
        /// <param name="dpMiscinfo">Хедър, съдържащ персонален идентификатор</param>
        /// <exception cref="ApiException">A server side error occurred.</exception>
        System.Threading.Tasks.Task<TableResultDOOfOutboxDO> GetOutboxAsync(string? dpMiscinfo, int? offset, int? limit, System.Threading.CancellationToken cancellationToken);

        /// <summary>
        /// Изпращане на съобщение
        /// </summary>
        /// <param name="dpMiscinfo">Хедър, съдържащ персонален идентификатор</param>
        /// <returns>Публичен идентификатор на изпратеното съобщение</returns>
        /// <exception cref="ApiException">A server side error occurred.</exception>
        System.Threading.Tasks.Task<int> SendAsync(string? dpMiscinfo, MessageSendDO message);

        /// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation.</param>
        /// <summary>
        /// Изпращане на съобщение
        /// </summary>
        /// <param name="dpMiscinfo">Хедър, съдържащ персонален идентификатор</param>
        /// <returns>Публичен идентификатор на изпратеното съобщение</returns>
        /// <exception cref="ApiException">A server side error occurred.</exception>
        System.Threading.Tasks.Task<int> SendAsync(string? dpMiscinfo, MessageSendDO message, System.Threading.CancellationToken cancellationToken);

        /// <summary>
        /// Преглед на получено съобщение
        /// </summary>
        /// <param name="dpMiscinfo">Хедър, съдържащ персонален идентификатор</param>
        /// <exception cref="ApiException">A server side error occurred.</exception>
        System.Threading.Tasks.Task<MessageOpenDO> OpenAsync(string? dpMiscinfo, int messageId);

        /// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation.</param>
        /// <summary>
        /// Преглед на получено съобщение
        /// </summary>
        /// <param name="dpMiscinfo">Хедър, съдържащ персонален идентификатор</param>
        /// <exception cref="ApiException">A server side error occurred.</exception>
        System.Threading.Tasks.Task<MessageOpenDO> OpenAsync(string? dpMiscinfo, int messageId, System.Threading.CancellationToken cancellationToken);

        /// <summary>
        /// Преглед на получено съобщение
        /// </summary>
        /// <param name="dpMiscinfo">Хедър, съдържащ персонален идентификатор</param>
        /// <exception cref="ApiException">A server side error occurred.</exception>
        System.Threading.Tasks.Task<ForwardedMessageOpenDO> OpenForwardedAsync(string? dpMiscinfo, int messageId, int forwardedMessageId);

        /// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation.</param>
        /// <summary>
        /// Преглед на получено съобщение
        /// </summary>
        /// <param name="dpMiscinfo">Хедър, съдържащ персонален идентификатор</param>
        /// <exception cref="ApiException">A server side error occurred.</exception>
        System.Threading.Tasks.Task<ForwardedMessageOpenDO> OpenForwardedAsync(string? dpMiscinfo, int messageId, int forwardedMessageId, System.Threading.CancellationToken cancellationToken);

        /// <summary>
        /// Преглед на изпратено съобщение
        /// </summary>
        /// <param name="dpMiscinfo">Хедър, съдържащ персонален идентификатор</param>
        /// <exception cref="ApiException">A server side error occurred.</exception>
        System.Threading.Tasks.Task<MessageViewDO> ViewAsync(string? dpMiscinfo, int messageId);

        /// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation.</param>
        /// <summary>
        /// Преглед на изпратено съобщение
        /// </summary>
        /// <param name="dpMiscinfo">Хедър, съдържащ персонален идентификатор</param>
        /// <exception cref="ApiException">A server side error occurred.</exception>
        System.Threading.Tasks.Task<MessageViewDO> ViewAsync(string? dpMiscinfo, int messageId, System.Threading.CancellationToken cancellationToken);

    }

    [System.CodeDom.Compiler.GeneratedCode("NSwag", "14.3.0.0 (NJsonSchema v11.2.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial interface IOboMessagesClient
    {
        /// <summary>
        /// Връща списък с получени съобщения от името на профил
        /// </summary>
        /// <param name="dpMiscinfo">Хедър, съдържащ персонален идентификатор</param>
        /// <exception cref="ApiException">A server side error occurred.</exception>
        System.Threading.Tasks.Task<TableResultDOOfInboxDO> GetInboxAsync(string? dpMiscinfo, int? offset, int? limit);

        /// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation.</param>
        /// <summary>
        /// Връща списък с получени съобщения от името на профил
        /// </summary>
        /// <param name="dpMiscinfo">Хедър, съдържащ персонален идентификатор</param>
        /// <exception cref="ApiException">A server side error occurred.</exception>
        System.Threading.Tasks.Task<TableResultDOOfInboxDO> GetInboxAsync(string? dpMiscinfo, int? offset, int? limit, System.Threading.CancellationToken cancellationToken);

        /// <summary>
        /// Връща списък с изпратени съобщения от името на профил
        /// </summary>
        /// <param name="dpMiscinfo">Хедър, съдържащ персонален идентификатор</param>
        /// <exception cref="ApiException">A server side error occurred.</exception>
        System.Threading.Tasks.Task<TableResultDOOfOutboxDO> GetOutboxAsync(string? dpMiscinfo, int? offset, int? limit);

        /// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation.</param>
        /// <summary>
        /// Връща списък с изпратени съобщения от името на профил
        /// </summary>
        /// <param name="dpMiscinfo">Хедър, съдържащ персонален идентификатор</param>
        /// <exception cref="ApiException">A server side error occurred.</exception>
        System.Threading.Tasks.Task<TableResultDOOfOutboxDO> GetOutboxAsync(string? dpMiscinfo, int? offset, int? limit, System.Threading.CancellationToken cancellationToken);

        /// <summary>
        /// Изпращане на съобщение от името на чужд профил
        /// </summary>
        /// <param name="dpMiscinfo">Хедър, съдържащ персонален идентификатор</param>
        /// <returns>Публичен идентификатор на изпратеното съобщение</returns>
        /// <exception cref="ApiException">A server side error occurred.</exception>
        System.Threading.Tasks.Task<int> SendAsync(string? dpMiscinfo, MessageSendOnBehalfOfDO message);

        /// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation.</param>
        /// <summary>
        /// Изпращане на съобщение от името на чужд профил
        /// </summary>
        /// <param name="dpMiscinfo">Хедър, съдържащ персонален идентификатор</param>
        /// <returns>Публичен идентификатор на изпратеното съобщение</returns>
        /// <exception cref="ApiException">A server side error occurred.</exception>
        System.Threading.Tasks.Task<int> SendAsync(string? dpMiscinfo, MessageSendOnBehalfOfDO message, System.Threading.CancellationToken cancellationToken);

    }

    [System.CodeDom.Compiler.GeneratedCode("NSwag", "14.3.0.0 (NJsonSchema v11.2.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial interface IOboProfilesClient
    {
        /// <summary>
        /// Връща профил, който може да получава съобщения, по даден идентификатор и шаблон на съобщението
        /// </summary>
        /// <param name="dpMiscinfo">Хедър, съдържащ персонален идентификатор</param>
        /// <exception cref="ApiException">A server side error occurred.</exception>
        System.Threading.Tasks.Task<ProfileDO> SearchAsync(string? dpMiscinfo, string? identifier, int? templateId, int targetGroupId);

        /// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation.</param>
        /// <summary>
        /// Връща профил, който може да получава съобщения, по даден идентификатор и шаблон на съобщението
        /// </summary>
        /// <param name="dpMiscinfo">Хедър, съдържащ персонален идентификатор</param>
        /// <exception cref="ApiException">A server side error occurred.</exception>
        System.Threading.Tasks.Task<ProfileDO> SearchAsync(string? dpMiscinfo, string? identifier, int? templateId, int targetGroupId, System.Threading.CancellationToken cancellationToken);

    }

    [System.CodeDom.Compiler.GeneratedCode("NSwag", "14.3.0.0 (NJsonSchema v11.2.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial interface IProfilesClient
    {
        /// <summary>
        /// Връща списък с активните профили в целева група
        /// </summary>
        /// <param name="dpMiscinfo">Хедър, съдържащ персонален идентификатор</param>
        /// <exception cref="ApiException">A server side error occurred.</exception>
        System.Threading.Tasks.Task<TableResultDOOfProfileDO> ListAsync(string? dpMiscinfo, int targetGroupId, int? offset, int? limit);

        /// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation.</param>
        /// <summary>
        /// Връща списък с активните профили в целева група
        /// </summary>
        /// <param name="dpMiscinfo">Хедър, съдържащ персонален идентификатор</param>
        /// <exception cref="ApiException">A server side error occurred.</exception>
        System.Threading.Tasks.Task<TableResultDOOfProfileDO> ListAsync(string? dpMiscinfo, int targetGroupId, int? offset, int? limit, System.Threading.CancellationToken cancellationToken);

        /// <summary>
        /// Връща профил, който може да получава съобщения, по даден идентификатор и шаблон на съобщението
        /// </summary>
        /// <param name="dpMiscinfo">Хедър, съдържащ персонален идентификатор</param>
        /// <exception cref="ApiException">A server side error occurred.</exception>
        System.Threading.Tasks.Task<ProfileDO> SearchAsync(string? dpMiscinfo, string? identifier, int? templateId, int targetGroupId);

        /// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation.</param>
        /// <summary>
        /// Връща профил, който може да получава съобщения, по даден идентификатор и шаблон на съобщението
        /// </summary>
        /// <param name="dpMiscinfo">Хедър, съдържащ персонален идентификатор</param>
        /// <exception cref="ApiException">A server side error occurred.</exception>
        System.Threading.Tasks.Task<ProfileDO> SearchAsync(string? dpMiscinfo, string? identifier, int? templateId, int targetGroupId, System.Threading.CancellationToken cancellationToken);

        /// <summary>
        /// Пасивна регистрация на профил на ФЛ, с цел получаване на съобщения и нотификации
        /// </summary>
        /// <param name="dpMiscinfo">Хедър, съдържащ персонален идентификатор</param>
        /// <param name="profile">Данни за регистрация на профил</param>
        /// <returns>Публичен идентификатор на регистрирания профил</returns>
        /// <exception cref="ApiException">A server side error occurred.</exception>
        System.Threading.Tasks.Task<int> RegisterIndividualAsync(string? dpMiscinfo, ProfileRegisterDO profile);

        /// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation.</param>
        /// <summary>
        /// Пасивна регистрация на профил на ФЛ, с цел получаване на съобщения и нотификации
        /// </summary>
        /// <param name="dpMiscinfo">Хедър, съдържащ персонален идентификатор</param>
        /// <param name="profile">Данни за регистрация на профил</param>
        /// <returns>Публичен идентификатор на регистрирания профил</returns>
        /// <exception cref="ApiException">A server side error occurred.</exception>
        System.Threading.Tasks.Task<int> RegisterIndividualAsync(string? dpMiscinfo, ProfileRegisterDO profile, System.Threading.CancellationToken cancellationToken);

    }

    [System.CodeDom.Compiler.GeneratedCode("NSwag", "14.3.0.0 (NJsonSchema v11.2.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial interface IStatisticsClient
    {
        /// <summary>
        /// Връща статистика за изпратените съобщения за период
        /// </summary>
        /// <param name="from">От дата</param>
        /// <param name="to">До дата</param>
        /// <exception cref="ApiException">A server side error occurred.</exception>
        System.Threading.Tasks.Task<int> GetSentMessagesStatisticsAsync(System.DateTimeOffset? from, System.DateTimeOffset? to);

        /// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation.</param>
        /// <summary>
        /// Връща статистика за изпратените съобщения за период
        /// </summary>
        /// <param name="from">От дата</param>
        /// <param name="to">До дата</param>
        /// <exception cref="ApiException">A server side error occurred.</exception>
        System.Threading.Tasks.Task<int> GetSentMessagesStatisticsAsync(System.DateTimeOffset? from, System.DateTimeOffset? to, System.Threading.CancellationToken cancellationToken);

        /// <summary>
        /// Връща статистика за получените съобщения за период
        /// </summary>
        /// <param name="from">От дата</param>
        /// <param name="to">До дата</param>
        /// <exception cref="ApiException">A server side error occurred.</exception>
        System.Threading.Tasks.Task<int> GetReceivedMessagesStatisticsAsync(System.DateTimeOffset? from, System.DateTimeOffset? to);

        /// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation.</param>
        /// <summary>
        /// Връща статистика за получените съобщения за период
        /// </summary>
        /// <param name="from">От дата</param>
        /// <param name="to">До дата</param>
        /// <exception cref="ApiException">A server side error occurred.</exception>
        System.Threading.Tasks.Task<int> GetReceivedMessagesStatisticsAsync(System.DateTimeOffset? from, System.DateTimeOffset? to, System.Threading.CancellationToken cancellationToken);

        /// <summary>
        /// Връща статистика за изпратените съобщения по месеци
        /// </summary>
        /// <exception cref="ApiException">A server side error occurred.</exception>
        System.Threading.Tasks.Task<int> GetSentMessagesMonthlyStatisticsAsync(System.DateTimeOffset? month);

        /// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation.</param>
        /// <summary>
        /// Връща статистика за изпратените съобщения по месеци
        /// </summary>
        /// <exception cref="ApiException">A server side error occurred.</exception>
        System.Threading.Tasks.Task<int> GetSentMessagesMonthlyStatisticsAsync(System.DateTimeOffset? month, System.Threading.CancellationToken cancellationToken);

        /// <summary>
        /// Връща статистика за получените съобщения по месеци
        /// </summary>
        /// <exception cref="ApiException">A server side error occurred.</exception>
        System.Threading.Tasks.Task<int> GetReceivedMessagesMonthlyStatisticsAsync(System.DateTimeOffset? month);

        /// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation.</param>
        /// <summary>
        /// Връща статистика за получените съобщения по месеци
        /// </summary>
        /// <exception cref="ApiException">A server side error occurred.</exception>
        System.Threading.Tasks.Task<int> GetReceivedMessagesMonthlyStatisticsAsync(System.DateTimeOffset? month, System.Threading.CancellationToken cancellationToken);

    }

    [System.CodeDom.Compiler.GeneratedCode("NSwag", "14.3.0.0 (NJsonSchema v11.2.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial interface ITargetGroupsClient
    {
        /// <summary>
        /// Връща списък с всички активни целеви групи
        /// </summary>
        /// <param name="dpMiscinfo">Хедър, съдържащ персонален идентификатор</param>
        /// <exception cref="ApiException">A server side error occurred.</exception>
        System.Threading.Tasks.Task<System.Collections.Generic.ICollection<TargetGroupDO>> ListAsync(string? dpMiscinfo);

        /// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation.</param>
        /// <summary>
        /// Връща списък с всички активни целеви групи
        /// </summary>
        /// <param name="dpMiscinfo">Хедър, съдържащ персонален идентификатор</param>
        /// <exception cref="ApiException">A server side error occurred.</exception>
        System.Threading.Tasks.Task<System.Collections.Generic.ICollection<TargetGroupDO>> ListAsync(string? dpMiscinfo, System.Threading.CancellationToken cancellationToken);

    }

    [System.CodeDom.Compiler.GeneratedCode("NSwag", "14.3.0.0 (NJsonSchema v11.2.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial interface IOboTemplatesClient
    {
        /// <summary>
        /// Връща списък с шаблоните на съобщението от името на профил, до които профила има достъп
        /// </summary>
        /// <param name="dpMiscinfo">Хедър, съдържащ персонален идентификатор</param>
        /// <exception cref="ApiException">A server side error occurred.</exception>
        System.Threading.Tasks.Task<System.Collections.Generic.ICollection<TemplateDO>> ListAsync(string? dpMiscinfo, int? offset, int? limit);

        /// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation.</param>
        /// <summary>
        /// Връща списък с шаблоните на съобщението от името на профил, до които профила има достъп
        /// </summary>
        /// <param name="dpMiscinfo">Хедър, съдържащ персонален идентификатор</param>
        /// <exception cref="ApiException">A server side error occurred.</exception>
        System.Threading.Tasks.Task<System.Collections.Generic.ICollection<TemplateDO>> ListAsync(string? dpMiscinfo, int? offset, int? limit, System.Threading.CancellationToken cancellationToken);

        /// <summary>
        /// Връща данните за шаблон на съобщение от името на профил
        /// </summary>
        /// <param name="dpMiscinfo">Хедър, съдържащ персонален идентификатор</param>
        /// <exception cref="ApiException">A server side error occurred.</exception>
        System.Threading.Tasks.Task<TemplateDetailsDO> DetailsAsync(string? dpMiscinfo, int templateId);

        /// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation.</param>
        /// <summary>
        /// Връща данните за шаблон на съобщение от името на профил
        /// </summary>
        /// <param name="dpMiscinfo">Хедър, съдържащ персонален идентификатор</param>
        /// <exception cref="ApiException">A server side error occurred.</exception>
        System.Threading.Tasks.Task<TemplateDetailsDO> DetailsAsync(string? dpMiscinfo, int templateId, System.Threading.CancellationToken cancellationToken);

    }

    [System.CodeDom.Compiler.GeneratedCode("NSwag", "14.3.0.0 (NJsonSchema v11.2.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial interface ITemplatesClient
    {
        /// <summary>
        /// Връща списък с шаблоните на съобщението, до които профила има достъп
        /// </summary>
        /// <param name="dpMiscinfo">Хедър, съдържащ персонален идентификатор</param>
        /// <exception cref="ApiException">A server side error occurred.</exception>
        System.Threading.Tasks.Task<System.Collections.Generic.ICollection<TemplateDO>> ListAsync(string? dpMiscinfo, int? offset, int? limit);

        /// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation.</param>
        /// <summary>
        /// Връща списък с шаблоните на съобщението, до които профила има достъп
        /// </summary>
        /// <param name="dpMiscinfo">Хедър, съдържащ персонален идентификатор</param>
        /// <exception cref="ApiException">A server side error occurred.</exception>
        System.Threading.Tasks.Task<System.Collections.Generic.ICollection<TemplateDO>> ListAsync(string? dpMiscinfo, int? offset, int? limit, System.Threading.CancellationToken cancellationToken);

        /// <summary>
        /// Връща данните за шаблон на съобщение
        /// </summary>
        /// <param name="dpMiscinfo">Хедър, съдържащ персонален идентификатор</param>
        /// <exception cref="ApiException">A server side error occurred.</exception>
        System.Threading.Tasks.Task<TemplateDetailsDO> DetailsAsync(string? dpMiscinfo, int templateId);

        /// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation.</param>
        /// <summary>
        /// Връща данните за шаблон на съобщение
        /// </summary>
        /// <param name="dpMiscinfo">Хедър, съдържащ персонален идентификатор</param>
        /// <exception cref="ApiException">A server side error occurred.</exception>
        System.Threading.Tasks.Task<TemplateDetailsDO> DetailsAsync(string? dpMiscinfo, int templateId, System.Threading.CancellationToken cancellationToken);

    }

    /// <summary>
    /// Списък обекти, използван при странициране
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.3.0.0 (NJsonSchema v11.2.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class TableResultDOOfBlobDO
    {
        [System.Text.Json.Serialization.JsonConstructor]

        public TableResultDOOfBlobDO(int @length, System.Collections.Generic.ICollection<BlobDO> @result)

        {

            this.Result = @result;

            this.Length = @length;

        }    /// <summary>
        /// Списък с обекти
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("result")]
        public System.Collections.Generic.ICollection<BlobDO> Result { get; }

        /// <summary>
        /// Общ брой обекти
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("length")]
        public int Length { get; }

    }

    /// <summary>
    /// Файл/документ
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.3.0.0 (NJsonSchema v11.2.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class BlobDO
    {
        [System.Text.Json.Serialization.JsonConstructor]

        public BlobDO(int @blobId, string? @documentRegistrationNumber, string @downloadLink, System.DateTimeOffset @downloadLinkExpirationDate, string @fileName, string? @hash, string? @hashAlgorithm, bool? @isMalicious, System.Collections.Generic.ICollection<MessageOpenDOBlobSignature> @signatures, long? @size)

        {

            this.BlobId = @blobId;

            this.FileName = @fileName;

            this.Size = @size;

            this.DocumentRegistrationNumber = @documentRegistrationNumber;

            this.IsMalicious = @isMalicious;

            this.Hash = @hash;

            this.HashAlgorithm = @hashAlgorithm;

            this.DownloadLink = @downloadLink;

            this.DownloadLinkExpirationDate = @downloadLinkExpirationDate;

            this.Signatures = @signatures;

        }    /// <summary>
        /// Идентификатор на файл
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("blobId")]
        public int BlobId { get; }

        /// <summary>
        /// Наименование на файл
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("fileName")]
        public string FileName { get; }

        /// <summary>
        /// Големина на файл (bytes)
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("size")]
        public long? Size { get; }

        /// <summary>
        /// Регистрационен номер на документ
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("documentRegistrationNumber")]
        public string? DocumentRegistrationNumber { get; }

        /// <summary>
        /// Флаг показващ дали файла съдържа зловреден код
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("isMalicious")]
        public bool? IsMalicious { get; }

        /// <summary>
        /// Хаш на файл
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("hash")]
        public string? Hash { get; }

        /// <summary>
        /// Алгоритъм за пресмятане на хаш на файл
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("hashAlgorithm")]
        public string? HashAlgorithm { get; }

        /// <summary>
        /// Линк за сваляне на файл
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("downloadLink")]
        public string DownloadLink { get; }

        /// <summary>
        /// Дата и час за валидност на линка за сваляне на файл
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("downloadLinkExpirationDate")]
        public System.DateTimeOffset DownloadLinkExpirationDate { get; }

        /// <summary>
        /// Списък ел. подписи, извлечени от файла
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("signatures")]
        public System.Collections.Generic.ICollection<MessageOpenDOBlobSignature> Signatures { get; }

    }

    /// <summary>
    /// Електронен подпис към файл
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.3.0.0 (NJsonSchema v11.2.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class MessageOpenDOBlobSignature
    {
        [System.Text.Json.Serialization.JsonConstructor]

        public MessageOpenDOBlobSignature(bool @coversDocument, string @issuer, bool @isTimestamp, System.DateTimeOffset @signDate, string @subject, bool @validAtTimeOfSigning, System.DateTimeOffset @validFrom, System.DateTimeOffset @validTo)

        {

            this.CoversDocument = @coversDocument;

            this.SignDate = @signDate;

            this.IsTimestamp = @isTimestamp;

            this.ValidAtTimeOfSigning = @validAtTimeOfSigning;

            this.Issuer = @issuer;

            this.Subject = @subject;

            this.ValidFrom = @validFrom;

            this.ValidTo = @validTo;

        }
        [System.Text.Json.Serialization.JsonPropertyName("coversDocument")]
        public bool CoversDocument { get; }

        [System.Text.Json.Serialization.JsonPropertyName("signDate")]
        public System.DateTimeOffset SignDate { get; }

        [System.Text.Json.Serialization.JsonPropertyName("isTimestamp")]
        public bool IsTimestamp { get; }

        [System.Text.Json.Serialization.JsonPropertyName("validAtTimeOfSigning")]
        public bool ValidAtTimeOfSigning { get; }

        [System.Text.Json.Serialization.JsonPropertyName("issuer")]
        public string Issuer { get; }

        [System.Text.Json.Serialization.JsonPropertyName("subject")]
        public string Subject { get; }

        [System.Text.Json.Serialization.JsonPropertyName("validFrom")]
        public System.DateTimeOffset ValidFrom { get; }

        [System.Text.Json.Serialization.JsonPropertyName("validTo")]
        public System.DateTimeOffset ValidTo { get; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.3.0.0 (NJsonSchema v11.2.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class ProblemDetails
    {
        [System.Text.Json.Serialization.JsonConstructor]

        public ProblemDetails(string? @detail, System.Collections.Generic.IDictionary<string, object> @extensions, string? @instance, int? @status, string? @title, string? @type)

        {

            this.Type = @type;

            this.Title = @title;

            this.Status = @status;

            this.Detail = @detail;

            this.Instance = @instance;

            this.Extensions = @extensions;

        }
        [System.Text.Json.Serialization.JsonPropertyName("type")]
        public string? Type { get; }

        [System.Text.Json.Serialization.JsonPropertyName("title")]
        public string? Title { get; }

        [System.Text.Json.Serialization.JsonPropertyName("status")]
        public int? Status { get; }

        [System.Text.Json.Serialization.JsonPropertyName("detail")]
        public string? Detail { get; }

        [System.Text.Json.Serialization.JsonPropertyName("instance")]
        public string? Instance { get; }

        [System.Text.Json.Serialization.JsonPropertyName("extensions")]
        public System.Collections.Generic.IDictionary<string, object> Extensions { get; }

        private System.Collections.Generic.IDictionary<string, object>? _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    /// <summary>
    /// Списък обекти, използван при странициране
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.3.0.0 (NJsonSchema v11.2.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class TableResultDOOfInboxDO
    {
        [System.Text.Json.Serialization.JsonConstructor]

        public TableResultDOOfInboxDO(int @length, System.Collections.Generic.ICollection<InboxDO> @result)

        {

            this.Result = @result;

            this.Length = @length;

        }    /// <summary>
        /// Списък с обекти
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("result")]
        public System.Collections.Generic.ICollection<InboxDO> Result { get; }

        /// <summary>
        /// Общ брой обекти
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("length")]
        public int Length { get; }

    }

    /// <summary>
    /// Получено съобщение
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.3.0.0 (NJsonSchema v11.2.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class InboxDO
    {
        [System.Text.Json.Serialization.JsonConstructor]

        public InboxDO(System.DateTimeOffset? @dateReceived, System.DateTimeOffset @dateSent, int @messageId, string @recipientLoginName, string @recipientProfileName, string? @rnu, string @senderLoginName, string @senderProfileName, string @subject, string @url)

        {

            this.MessageId = @messageId;

            this.DateSent = @dateSent;

            this.DateReceived = @dateReceived;

            this.Subject = @subject;

            this.SenderProfileName = @senderProfileName;

            this.SenderLoginName = @senderLoginName;

            this.RecipientProfileName = @recipientProfileName;

            this.RecipientLoginName = @recipientLoginName;

            this.Url = @url;

            this.Rnu = @rnu;

        }    /// <summary>
        /// Идентификатор на съобщение
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("messageId")]
        public int MessageId { get; }

        /// <summary>
        /// Дата на изпращане
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("dateSent")]
        public System.DateTimeOffset DateSent { get; }

        /// <summary>
        /// Дата получаване/отваряне
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("dateReceived")]
        public System.DateTimeOffset? DateReceived { get; }

        /// <summary>
        /// Заглавие на съобщение
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("subject")]
        public string Subject { get; }

        /// <summary>
        /// Наименование на профила изпращач
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("senderProfileName")]
        public string SenderProfileName { get; }

        /// <summary>
        /// Наименование на потребител, изпратил съобщението
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("senderLoginName")]
        public string SenderLoginName { get; }

        /// <summary>
        /// Наименование на профила получател
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("recipientProfileName")]
        public string RecipientProfileName { get; }

        /// <summary>
        /// Наименование на потребител, получил съобщението
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("recipientLoginName")]
        public string RecipientLoginName { get; }

        /// <summary>
        /// Url за преглед на съобщението в ССЕВ
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("url")]
        public string Url { get; }

        /// <summary>
        /// Референтен номер на услуга (РНУ)
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("rnu")]
        public string? Rnu { get; }

    }

    /// <summary>
    /// Списък обекти, използван при странициране
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.3.0.0 (NJsonSchema v11.2.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class TableResultDOOfOutboxDO
    {
        [System.Text.Json.Serialization.JsonConstructor]

        public TableResultDOOfOutboxDO(int @length, System.Collections.Generic.ICollection<OutboxDO> @result)

        {

            this.Result = @result;

            this.Length = @length;

        }    /// <summary>
        /// Списък с обекти
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("result")]
        public System.Collections.Generic.ICollection<OutboxDO> Result { get; }

        /// <summary>
        /// Общ брой обекти
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("length")]
        public int Length { get; }

    }

    /// <summary>
    /// Изпратено съобщение
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.3.0.0 (NJsonSchema v11.2.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class OutboxDO
    {
        [System.Text.Json.Serialization.JsonConstructor]

        public OutboxDO(System.DateTimeOffset @dateSent, int @messageId, string @recipients, string? @rnu, string @senderLoginName, string @senderProfileName, string @subject, string @url)

        {

            this.MessageId = @messageId;

            this.DateSent = @dateSent;

            this.Subject = @subject;

            this.SenderProfileName = @senderProfileName;

            this.SenderLoginName = @senderLoginName;

            this.Recipients = @recipients;

            this.Url = @url;

            this.Rnu = @rnu;

        }    /// <summary>
        /// Идентификатор на съобщение
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("messageId")]
        public int MessageId { get; }

        /// <summary>
        /// Дата на изпращане
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("dateSent")]
        public System.DateTimeOffset DateSent { get; }

        /// <summary>
        /// Заглавие на съобщение
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("subject")]
        public string Subject { get; }

        /// <summary>
        /// Наименование на профила изпращач
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("senderProfileName")]
        public string SenderProfileName { get; }

        /// <summary>
        /// Наименование на потребител, изпратил съобщението
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("senderLoginName")]
        public string SenderLoginName { get; }

        /// <summary>
        /// Получатели като текст
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("recipients")]
        public string Recipients { get; }

        /// <summary>
        /// Url за преглед на съобщението в ССЕВ
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("url")]
        public string Url { get; }

        /// <summary>
        /// Референтен номер на услуга (РНУ)
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("rnu")]
        public string? Rnu { get; }

    }

    /// <summary>
    /// Модел за изпращане на съобщение
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.3.0.0 (NJsonSchema v11.2.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class MessageSendDO
    {
        [System.Text.Json.Serialization.JsonConstructor]

        public MessageSendDO(System.Collections.Generic.IDictionary<string, object> @fields, System.Collections.Generic.ICollection<int> @recipientProfileIds, string? @rnu, string @subject, int @templateId)

        {

            this.RecipientProfileIds = @recipientProfileIds;

            this.Subject = @subject;

            this.Rnu = @rnu;

            this.TemplateId = @templateId;

            this.Fields = @fields;

        }    /// <summary>
        /// Списък идентификатори на получатели
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("recipientProfileIds")]
        public System.Collections.Generic.ICollection<int> RecipientProfileIds { get; }

        /// <summary>
        /// Заглавие на съобщението
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("subject")]
        public string Subject { get; }

        /// <summary>
        /// Референтен номер на услуга (РНУ)
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("rnu")]
        public string? Rnu { get; }

        /// <summary>
        /// Шаблон на съобщението
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("templateId")]
        public int TemplateId { get; }

        /// <summary>
        /// Списък с полетата и техните стойности в шаблона на съобщението във формат (Идентификатор на поле, Стойност)
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("fields")]
        public System.Collections.Generic.IDictionary<string, object> Fields { get; }

    }

    /// <summary>
    /// Данни за получено съобщение
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.3.0.0 (NJsonSchema v11.2.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class MessageOpenDO
    {
        [System.Text.Json.Serialization.JsonConstructor]

        public MessageOpenDO(System.DateTimeOffset? @dateReceived, System.DateTimeOffset @dateSent, System.Collections.Generic.IDictionary<string, object> @fields, int? @forwardedMessageId, int @messageId, MessageOpenDORecipientLogin? @recipientLogin, string? @rnu, MessageOpenDOSenderProfile @sender, string @subject, int @templateId)

        {

            this.MessageId = @messageId;

            this.DateSent = @dateSent;

            this.Sender = @sender;

            this.DateReceived = @dateReceived;

            this.RecipientLogin = @recipientLogin;

            this.Subject = @subject;

            this.Rnu = @rnu;

            this.TemplateId = @templateId;

            this.Fields = @fields;

            this.ForwardedMessageId = @forwardedMessageId;

        }    /// <summary>
        /// Идентификатор на съобщение
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("messageId")]
        public int MessageId { get; }

        /// <summary>
        /// Дата на изпращане
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("dateSent")]
        public System.DateTimeOffset DateSent { get; }

        /// <summary>
        /// Профил изпращач
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("sender")]
        public MessageOpenDOSenderProfile Sender { get; }

        /// <summary>
        /// Дата на отваряне на съобщението
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("dateReceived")]
        public System.DateTimeOffset? DateReceived { get; }

        /// <summary>
        /// Потребител отворил съобщението
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("recipientLogin")]
        public MessageOpenDORecipientLogin? RecipientLogin { get; }

        /// <summary>
        /// Заглавие на съобщение
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("subject")]
        public string Subject { get; }

        /// <summary>
        /// Референтен номер на услуга (РНУ)
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("rnu")]
        public string? Rnu { get; }

        /// <summary>
        /// Идентификатор на шаблон на съобщение
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("templateId")]
        public int TemplateId { get; }

        /// <summary>
        /// Списък с полета и техните стойности в шаблона на съобщението във формат (Идентификатор на поле, Стойност)
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("fields")]
        public System.Collections.Generic.IDictionary<string, object> Fields { get; }

        /// <summary>
        /// Идентификатор на препратено съобщение
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("forwardedMessageId")]
        public int? ForwardedMessageId { get; }

    }

    /// <summary>
    /// Профил, изпращач на съобщение
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.3.0.0 (NJsonSchema v11.2.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class MessageOpenDOSenderProfile
    {
        [System.Text.Json.Serialization.JsonConstructor]

        public MessageOpenDOSenderProfile(string @name, int @profileId)

        {

            this.ProfileId = @profileId;

            this.Name = @name;

        }    /// <summary>
        /// Идентификатор на профил
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("profileId")]
        public int ProfileId { get; }

        /// <summary>
        /// Наименование на профил
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("name")]
        public string Name { get; }

    }

    /// <summary>
    /// Потребител, отворил съобщението
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.3.0.0 (NJsonSchema v11.2.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class MessageOpenDORecipientLogin
    {
        [System.Text.Json.Serialization.JsonConstructor]

        public MessageOpenDORecipientLogin(int @loginId, string @name)

        {

            this.LoginId = @loginId;

            this.Name = @name;

        }    /// <summary>
        /// Идентификатор на потребител
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("loginId")]
        public int LoginId { get; }

        /// <summary>
        /// Наименование на потребител
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("name")]
        public string Name { get; }

    }

    /// <summary>
    /// Данни за получено препратено съобщение
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.3.0.0 (NJsonSchema v11.2.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class ForwardedMessageOpenDO
    {
        [System.Text.Json.Serialization.JsonConstructor]

        public ForwardedMessageOpenDO(System.DateTimeOffset? @dateReceived, System.DateTimeOffset @dateSent, System.Collections.Generic.IDictionary<string, object> @fields, int? @forwardedMessageId, int @messageId, ForwardedMessageOpenDORecipientProfile @recipient, ForwardedMessageOpenDORecipientLogin? @recipientLogin, string? @rnu, ForwardedMessageOpenDOSenderProfile @sender, string @subject, int @templateId)

        {

            this.MessageId = @messageId;

            this.DateSent = @dateSent;

            this.Sender = @sender;

            this.DateReceived = @dateReceived;

            this.Recipient = @recipient;

            this.RecipientLogin = @recipientLogin;

            this.Subject = @subject;

            this.Rnu = @rnu;

            this.TemplateId = @templateId;

            this.Fields = @fields;

            this.ForwardedMessageId = @forwardedMessageId;

        }    /// <summary>
        /// Идентификатор на съобщение
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("messageId")]
        public int MessageId { get; }

        /// <summary>
        /// Дата на изпращане
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("dateSent")]
        public System.DateTimeOffset DateSent { get; }

        /// <summary>
        /// Профил изпращач
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("sender")]
        public ForwardedMessageOpenDOSenderProfile Sender { get; }

        /// <summary>
        /// Дата на отваряне на съобщението
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("dateReceived")]
        public System.DateTimeOffset? DateReceived { get; }

        [System.Text.Json.Serialization.JsonPropertyName("recipient")]
        public ForwardedMessageOpenDORecipientProfile Recipient { get; }

        /// <summary>
        /// Потребител отворил съобщението
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("recipientLogin")]
        public ForwardedMessageOpenDORecipientLogin? RecipientLogin { get; }

        /// <summary>
        /// Заглавие на съобщение
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("subject")]
        public string Subject { get; }

        /// <summary>
        /// Референтен номер на услуга (РНУ)
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("rnu")]
        public string? Rnu { get; }

        /// <summary>
        /// Идентификатор на шаблон на съобщение
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("templateId")]
        public int TemplateId { get; }

        /// <summary>
        /// Списък с полета и техните стойности в шаблона на съобщението във формат (Идентификатор на поле, Стойност)
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("fields")]
        public System.Collections.Generic.IDictionary<string, object> Fields { get; }

        /// <summary>
        /// Идентификатор на препратено съобщение
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("forwardedMessageId")]
        public int? ForwardedMessageId { get; }

    }

    /// <summary>
    /// Профил, изпращач на съобщение
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.3.0.0 (NJsonSchema v11.2.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class ForwardedMessageOpenDOSenderProfile
    {
        [System.Text.Json.Serialization.JsonConstructor]

        public ForwardedMessageOpenDOSenderProfile(string @name, int @profileId)

        {

            this.ProfileId = @profileId;

            this.Name = @name;

        }    /// <summary>
        /// Идентификатор на профил
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("profileId")]
        public int ProfileId { get; }

        /// <summary>
        /// Наименование на профил
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("name")]
        public string Name { get; }

    }

    /// <summary>
    /// Профил, получател на съобщение
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.3.0.0 (NJsonSchema v11.2.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class ForwardedMessageOpenDORecipientProfile
    {
        [System.Text.Json.Serialization.JsonConstructor]

        public ForwardedMessageOpenDORecipientProfile(string @name, int @profileId)

        {

            this.ProfileId = @profileId;

            this.Name = @name;

        }    /// <summary>
        /// Идентификатор на профил
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("profileId")]
        public int ProfileId { get; }

        /// <summary>
        /// Наименование на профил
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("name")]
        public string Name { get; }

    }

    /// <summary>
    /// Потребител, отворил съобщението
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.3.0.0 (NJsonSchema v11.2.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class ForwardedMessageOpenDORecipientLogin
    {
        [System.Text.Json.Serialization.JsonConstructor]

        public ForwardedMessageOpenDORecipientLogin(int @loginId, string @name)

        {

            this.LoginId = @loginId;

            this.Name = @name;

        }    /// <summary>
        /// Идентификатор на потребител
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("loginId")]
        public int LoginId { get; }

        /// <summary>
        /// Наименование на потребител
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("name")]
        public string Name { get; }

    }

    /// <summary>
    /// Данни за изпратено съобщение
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.3.0.0 (NJsonSchema v11.2.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class MessageViewDO
    {
        [System.Text.Json.Serialization.JsonConstructor]

        public MessageViewDO(System.DateTimeOffset @dateSent, System.Collections.Generic.IDictionary<string, object> @fields, int? @forwardedMessageId, int @messageId, System.Collections.Generic.ICollection<MessageViewDORecipient> @recipients, string? @rnu, string @subject, int @templateId)

        {

            this.MessageId = @messageId;

            this.DateSent = @dateSent;

            this.Recipients = @recipients;

            this.Subject = @subject;

            this.Rnu = @rnu;

            this.TemplateId = @templateId;

            this.Fields = @fields;

            this.ForwardedMessageId = @forwardedMessageId;

        }    /// <summary>
        /// Идентификатор на съобщение
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("messageId")]
        public int MessageId { get; }

        /// <summary>
        /// Дата на изпращане
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("dateSent")]
        public System.DateTimeOffset DateSent { get; }

        /// <summary>
        /// Списък с получатели на съобщението
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("recipients")]
        public System.Collections.Generic.ICollection<MessageViewDORecipient> Recipients { get; }

        /// <summary>
        /// Заглавие на съобщение
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("subject")]
        public string Subject { get; }

        /// <summary>
        /// Референтен номер на услуга (РНУ)
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("rnu")]
        public string? Rnu { get; }

        /// <summary>
        /// Идентификатор на шаблон на съобщение
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("templateId")]
        public int TemplateId { get; }

        /// <summary>
        /// Списък с полета и техните стойности в шаблона на съобщението във формат (Идентификатор на поле, Стойност)
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("fields")]
        public System.Collections.Generic.IDictionary<string, object> Fields { get; }

        /// <summary>
        /// Идентификатор на препратено съобщение
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("forwardedMessageId")]
        public int? ForwardedMessageId { get; }

    }

    /// <summary>
    /// Получател на съобщение
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.3.0.0 (NJsonSchema v11.2.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class MessageViewDORecipient
    {
        [System.Text.Json.Serialization.JsonConstructor]

        public MessageViewDORecipient(System.DateTimeOffset? @dateReceived, string @name, int @profileId)

        {

            this.ProfileId = @profileId;

            this.Name = @name;

            this.DateReceived = @dateReceived;

        }    /// <summary>
        /// Идентификатор на профил получател
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("profileId")]
        public int ProfileId { get; }

        /// <summary>
        /// Наименование на профил получател
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("name")]
        public string Name { get; }

        /// <summary>
        /// Дата на получаване на съобщение
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("dateReceived")]
        public System.DateTimeOffset? DateReceived { get; }

    }

    /// <summary>
    /// Модел за изпращане на съобщение от името на чужд профил
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.3.0.0 (NJsonSchema v11.2.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class MessageSendOnBehalfOfDO
    {
        [System.Text.Json.Serialization.JsonConstructor]

        public MessageSendOnBehalfOfDO(System.Collections.Generic.IDictionary<string, object> @fields, System.Collections.Generic.ICollection<int> @recipientProfileIds, string? @rnu, string @subject, int @templateId)

        {

            this.RecipientProfileIds = @recipientProfileIds;

            this.Subject = @subject;

            this.Rnu = @rnu;

            this.TemplateId = @templateId;

            this.Fields = @fields;

        }    /// <summary>
        /// Списък идентификатори на получатели
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("recipientProfileIds")]
        public System.Collections.Generic.ICollection<int> RecipientProfileIds { get; }

        /// <summary>
        /// Заглавие на съобщението
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("subject")]
        public string Subject { get; }

        /// <summary>
        /// Референтен номер на услуга (РНУ)
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("rnu")]
        public string? Rnu { get; }

        /// <summary>
        /// Шаблон на съобщението
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("templateId")]
        public int TemplateId { get; }

        /// <summary>
        /// Списък с полетата и техните стойности в шаблона на съобщението във формат (Идентификатор на поле, Стойност)
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("fields")]
        public System.Collections.Generic.IDictionary<string, object> Fields { get; }

    }

    /// <summary>
    /// Документ
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.3.0.0 (NJsonSchema v11.2.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class ProfileDO
    {
        [System.Text.Json.Serialization.JsonConstructor]

        public ProfileDO(string @email, string @identifier, string @name, string @phone, int @profileId)

        {

            this.ProfileId = @profileId;

            this.Identifier = @identifier;

            this.Name = @name;

            this.Email = @email;

            this.Phone = @phone;

        }    /// <summary>
        /// Публичен идентификатор на профил
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("profileId")]
        public int ProfileId { get; }

        /// <summary>
        /// Идентификатор на профил
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("identifier")]
        public string Identifier { get; }

        /// <summary>
        /// Наименование на профил
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("name")]
        public string Name { get; }

        /// <summary>
        /// Имейл на профил
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("email")]
        public string Email { get; }

        /// <summary>
        /// Телефон на профил
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("phone")]
        public string Phone { get; }

    }

    /// <summary>
    /// Списък обекти, използван при странициране
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.3.0.0 (NJsonSchema v11.2.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class TableResultDOOfProfileDO
    {
        [System.Text.Json.Serialization.JsonConstructor]

        public TableResultDOOfProfileDO(int @length, System.Collections.Generic.ICollection<ProfileDO> @result)

        {

            this.Result = @result;

            this.Length = @length;

        }    /// <summary>
        /// Списък с обекти
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("result")]
        public System.Collections.Generic.ICollection<ProfileDO> Result { get; }

        /// <summary>
        /// Общ брой обекти
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("length")]
        public int Length { get; }

    }

    /// <summary>
    /// Пасивна регистрация на профил на ЮЛ
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.3.0.0 (NJsonSchema v11.2.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class ProfileRegisterDO
    {
        [System.Text.Json.Serialization.JsonConstructor]

        public ProfileRegisterDO(string @email, string @firstName, string @identifier, string @lastName, string @middleName, string @phone, string @residence)

        {

            this.Identifier = @identifier;

            this.FirstName = @firstName;

            this.MiddleName = @middleName;

            this.LastName = @lastName;

            this.Email = @email;

            this.Phone = @phone;

            this.Residence = @residence;

        }    /// <summary>
        /// Идентификатор на профила ЕГН/ЛНЧ
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("identifier")]
        public string Identifier { get; }

        /// <summary>
        /// Собствено име
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("firstName")]
        public string FirstName { get; }

        /// <summary>
        /// Бащино име
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("middleName")]
        public string MiddleName { get; }

        /// <summary>
        /// Фамилия
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("lastName")]
        public string LastName { get; }

        /// <summary>
        /// Имейл за нотификация
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("email")]
        public string Email { get; }

        /// <summary>
        /// Телефон за нотификация
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("phone")]
        public string Phone { get; }

        [System.Text.Json.Serialization.JsonPropertyName("residence")]
        public string Residence { get; }

    }

    /// <summary>
    /// Целева група
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.3.0.0 (NJsonSchema v11.2.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class TargetGroupDO
    {
        [System.Text.Json.Serialization.JsonConstructor]

        public TargetGroupDO(bool @canSelectRecipients, string @name, int @targetGroupId)

        {

            this.TargetGroupId = @targetGroupId;

            this.Name = @name;

            this.CanSelectRecipients = @canSelectRecipients;

        }    /// <summary>
        /// Идентификатор на целева група
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("targetGroupId")]
        public int TargetGroupId { get; }

        /// <summary>
        /// Наименование на целева група
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("name")]
        public string Name { get; }

        /// <summary>
        /// Възможност за преглед на профили от целевата група и възможност за избиране на получатели от нея
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("canSelectRecipients")]
        public bool CanSelectRecipients { get; }

    }

    /// <summary>
    /// Шаблон на съобщение
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.3.0.0 (NJsonSchema v11.2.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class TemplateDO
    {
        [System.Text.Json.Serialization.JsonConstructor]

        public TemplateDO(string @identityNumber, string @name, TemplateSecurityLevel @read, int? @responseTemplateId, int @templateId, TemplateSecurityLevel @write)

        {

            this.TemplateId = @templateId;

            this.Name = @name;

            this.IdentityNumber = @identityNumber;

            this.Read = @read;

            this.Write = @write;

            this.ResponseTemplateId = @responseTemplateId;

        }    /// <summary>
        /// Идентификатор на шаблон
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("templateId")]
        public int TemplateId { get; }

        /// <summary>
        /// Наименование на шаблон
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("name")]
        public string Name { get; }

        /// <summary>
        /// Номер на шаблон
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("identityNumber")]
        public string IdentityNumber { get; }

        /// <summary>
        /// Мин. ниво на осигуреност нужно за получаване на съобщение със съответния шаблон
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("read")]
        public TemplateSecurityLevel Read { get; }

        /// <summary>
        /// Мин. ниво на осигуреност нужно за изпращане на съобщение със съответния шаблон
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("write")]
        public TemplateSecurityLevel Write { get; }

        /// <summary>
        /// Шаблон на съобщение при отговор
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("responseTemplateId")]
        public int? ResponseTemplateId { get; }

    }

    /// <summary>
    /// Ниво на осигуреност на шаблон на съобщение
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.3.0.0 (NJsonSchema v11.2.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public enum TemplateSecurityLevel
    {

        LOW = 1,

        MEDIUM = 2,

        HIGH = 3,

    }

    /// <summary>
    /// Шаблон на съобщение
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.3.0.0 (NJsonSchema v11.2.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class TemplateDetailsDO
    {
        [System.Text.Json.Serialization.JsonConstructor]

        public TemplateDetailsDO(System.Collections.Generic.ICollection<BaseComponent> @content, string @identityNumber, string @name, TemplateSecurityLevel @read, int? @responseTemplateId, int @templateId, TemplateSecurityLevel @write)

        {

            this.TemplateId = @templateId;

            this.Name = @name;

            this.IdentityNumber = @identityNumber;

            this.Read = @read;

            this.Write = @write;

            this.Content = @content;

            this.ResponseTemplateId = @responseTemplateId;

        }    /// <summary>
        /// Идентификатор на шаблон
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("templateId")]
        public int TemplateId { get; }

        /// <summary>
        /// Наименование на шаблон
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("name")]
        public string Name { get; }

        /// <summary>
        /// Номер на шаблон
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("identityNumber")]
        public string IdentityNumber { get; }

        /// <summary>
        /// Мин. ниво на осигуреност нужно за получаване на съобщение със съответния шаблон
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("read")]
        public TemplateSecurityLevel Read { get; }

        /// <summary>
        /// Мин. ниво на осигуреност нужно за изпращане на съобщение със съответния шаблон
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("write")]
        public TemplateSecurityLevel Write { get; }

        /// <summary>
        /// Списък с полетата в шаблона
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("content")]
        public System.Collections.Generic.ICollection<BaseComponent> Content { get; }

        /// <summary>
        /// Шаблон на съобщение при отговор
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("responseTemplateId")]
        public int? ResponseTemplateId { get; }

    }

    /// <summary>
    /// Базов клас за поле в шаблон. 
    /// <br/>Спрямо полето "discriminator" се сериализира до следните класове: CheckboxComponent, FileComponent, DateTimeComponent, HiddenComponent, SelectComponent, TextAreaComponent, TextFieldComponent и MarkdownComponent.
    /// </summary>
    [JsonInheritanceConverter(typeof(BaseComponent), "discriminator")]
    [JsonInheritanceAttribute("CheckboxComponent", typeof(CheckboxComponent))]
    [JsonInheritanceAttribute("FileComponent", typeof(FileComponent))]
    [JsonInheritanceAttribute("DateTimeComponent", typeof(DateTimeComponent))]
    [JsonInheritanceAttribute("HiddenComponent", typeof(HiddenComponent))]
    [JsonInheritanceAttribute("SelectComponent", typeof(SelectComponent))]
    [JsonInheritanceAttribute("TextAreaComponent", typeof(TextAreaComponent))]
    [JsonInheritanceAttribute("TextFieldComponent", typeof(TextFieldComponent))]
    [JsonInheritanceAttribute("MarkdownComponent", typeof(MarkdownComponent))]
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.3.0.0 (NJsonSchema v11.2.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public abstract partial class BaseComponent
    {
        [System.Text.Json.Serialization.JsonConstructor]

        protected BaseComponent(System.Guid @id, bool @isEncrypted, bool @isRequired, string @label, ComponentType @type)

        {

            this.Id = @id;

            this.Label = @label;

            this.Type = @type;

            this.IsEncrypted = @isEncrypted;

            this.IsRequired = @isRequired;

        }    /// <summary>
        /// Идентификатор на поле
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("id")]
        public System.Guid Id { get; }

        /// <summary>
        /// Наименование на поле
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("label")]
        public string Label { get; }

        /// <summary>
        /// Тип на поле
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("type")]
        [System.Text.Json.Serialization.JsonConverter(typeof(System.Text.Json.Serialization.JsonStringEnumConverter))]
        public ComponentType Type { get; }

        /// <summary>
        /// Дали данните от полето се криптират
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("isEncrypted")]
        public bool IsEncrypted { get; }

        /// <summary>
        /// Дали полето е задължително за попълване
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("isRequired")]
        public bool IsRequired { get; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.3.0.0 (NJsonSchema v11.2.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public enum ComponentType
    {

        [System.Runtime.Serialization.EnumMember(Value = @"hidden")]
        Hidden = 0,

        [System.Runtime.Serialization.EnumMember(Value = @"textfield")]
        Textfield = 1,

        [System.Runtime.Serialization.EnumMember(Value = @"textarea")]
        Textarea = 2,

        [System.Runtime.Serialization.EnumMember(Value = @"datetime")]
        Datetime = 3,

        [System.Runtime.Serialization.EnumMember(Value = @"checkbox")]
        Checkbox = 4,

        [System.Runtime.Serialization.EnumMember(Value = @"select")]
        Select = 5,

        [System.Runtime.Serialization.EnumMember(Value = @"file")]
        File = 6,

        [System.Runtime.Serialization.EnumMember(Value = @"markdown")]
        Markdown = 7,

    }

    /// <summary>
    /// Поле тип "checkbox"
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.3.0.0 (NJsonSchema v11.2.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class CheckboxComponent : BaseComponent
    {
        [System.Text.Json.Serialization.JsonConstructor]

        public CheckboxComponent(System.Guid @id, bool @isEncrypted, bool @isRequired, string @label, ComponentType @type, bool @value)

            : base(id, isEncrypted, isRequired, label, type)

        {

            this.Value = @value;

        }    /// <summary>
        /// Стойност на полето
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("value")]
        public bool Value { get; }

    }

    /// <summary>
    /// Поле тип "file"
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.3.0.0 (NJsonSchema v11.2.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class FileComponent : BaseComponent
    {
        [System.Text.Json.Serialization.JsonConstructor]

        public FileComponent(string? @allowedExtensions, int @expirationPeriod, System.Guid @id, int @instances, bool @isEncrypted, bool @isRequired, string @label, int @maxSize, ComponentType @type)

            : base(id, isEncrypted, isRequired, label, type)

        {

            this.MaxSize = @maxSize;

            this.ExpirationPeriod = @expirationPeriod;

            this.AllowedExtensions = @allowedExtensions;

            this.Instances = @instances;

        }    /// <summary>
        /// Максимална големина на прикачения файл
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("maxSize")]
        public int MaxSize { get; }

        /// <summary>
        /// Време до архивиране (в месеци)
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("expirationPeriod")]
        public int ExpirationPeriod { get; }

        /// <summary>
        /// Позволени вид файлове
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("allowedExtensions")]
        public string? AllowedExtensions { get; }

        /// <summary>
        /// Максимален брой прикачени файлове
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("instances")]
        public int Instances { get; }

    }

    /// <summary>
    /// Поле тип "datetime"
    /// <br/>            
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.3.0.0 (NJsonSchema v11.2.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class DateTimeComponent : ValueComponent
    {
        [System.Text.Json.Serialization.JsonConstructor]

        public DateTimeComponent(System.Guid @id, bool @isEncrypted, bool @isRequired, string @label, ComponentType @type, string? @value)

            : base(id, isEncrypted, isRequired, label, type, value)

        {

        }
    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.3.0.0 (NJsonSchema v11.2.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public abstract partial class ValueComponent : BaseComponent
    {
        [System.Text.Json.Serialization.JsonConstructor]

        protected ValueComponent(System.Guid @id, bool @isEncrypted, bool @isRequired, string @label, ComponentType @type, string? @value)

            : base(id, isEncrypted, isRequired, label, type)

        {

            this.Value = @value;

        }
        [System.Text.Json.Serialization.JsonPropertyName("value")]
        public string? Value { get; }

    }

    /// <summary>
    /// Поле тип "hidden"
    /// <br/>            
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.3.0.0 (NJsonSchema v11.2.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class HiddenComponent : ValueComponent
    {
        [System.Text.Json.Serialization.JsonConstructor]

        public HiddenComponent(System.Guid @id, bool @isEncrypted, bool @isRequired, string @label, ComponentType @type, string? @value)

            : base(id, isEncrypted, isRequired, label, type, value)

        {

        }
    }

    /// <summary>
    /// Поле тип "select"
    /// <br/>            
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.3.0.0 (NJsonSchema v11.2.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class SelectComponent : ValueComponent
    {
        [System.Text.Json.Serialization.JsonConstructor]

        public SelectComponent(System.Guid @id, bool @isEncrypted, bool @isRequired, string @label, System.Collections.Generic.ICollection<string> @options, ComponentType @type, string? @url, string? @value)

            : base(id, isEncrypted, isRequired, label, type, value)

        {

            this.Url = @url;

            this.Options = @options;

        }    /// <summary>
        /// Url за зареждане на възможните стойности на полето
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("url")]
        public string? Url { get; }

        /// <summary>
        /// Списък с възможни стойности на полето
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("options")]
        public System.Collections.Generic.ICollection<string> Options { get; }

    }

    /// <summary>
    /// Поле тип "textarea"
    /// <br/>            
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.3.0.0 (NJsonSchema v11.2.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class TextAreaComponent : ValueComponent
    {
        [System.Text.Json.Serialization.JsonConstructor]

        public TextAreaComponent(System.Guid @id, bool @isEncrypted, bool @isRequired, string @label, ComponentType @type, string? @value)

            : base(id, isEncrypted, isRequired, label, type, value)

        {

        }
    }

    /// <summary>
    /// Поле тип "textfield"
    /// <br/>            
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.3.0.0 (NJsonSchema v11.2.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class TextFieldComponent : ValueComponent
    {
        [System.Text.Json.Serialization.JsonConstructor]

        public TextFieldComponent(System.Guid @id, bool @isEncrypted, bool @isRequired, string @label, ComponentType @type, string? @value)

            : base(id, isEncrypted, isRequired, label, type, value)

        {

        }
    }

    /// <summary>
    /// Поле тип "markdown"
    /// <br/>            
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.3.0.0 (NJsonSchema v11.2.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class MarkdownComponent : ValueComponent
    {
        [System.Text.Json.Serialization.JsonConstructor]

        public MarkdownComponent(System.Guid @id, bool @isEncrypted, bool @isRequired, string @label, string? @pdfValue, ComponentType @type, string? @value)

            : base(id, isEncrypted, isRequired, label, type, value)

        {

            this.PdfValue = @pdfValue;

        }    /// <summary>
        /// Стойност на полето в PDF експорт
        /// </summary>

        [System.Text.Json.Serialization.JsonPropertyName("pdfValue")]
        public string? PdfValue { get; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.3.0.0 (NJsonSchema v11.2.0.0 (Newtonsoft.Json v13.0.0.0))")]
    [System.AttributeUsage(System.AttributeTargets.Class | System.AttributeTargets.Interface, AllowMultiple = true)]
    internal class JsonInheritanceAttribute : System.Attribute
    {
        public JsonInheritanceAttribute(string key, System.Type type)
        {
            Key = key;
            Type = type;
        }

        public string Key { get; }

        public System.Type Type { get; }
    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.3.0.0 (NJsonSchema v11.2.0.0 (Newtonsoft.Json v13.0.0.0))")]
    internal class JsonInheritanceConverterAttribute : System.Text.Json.Serialization.JsonConverterAttribute
    {
        public string DiscriminatorName { get; }

        public JsonInheritanceConverterAttribute(System.Type baseType, string discriminatorName = "discriminator")
            : base(typeof(JsonInheritanceConverter<>).MakeGenericType(baseType))
        {
            DiscriminatorName = discriminatorName;
        }
    }

    public class JsonInheritanceConverter<TBase> : System.Text.Json.Serialization.JsonConverter<TBase>
    {
        private readonly string _discriminatorName;

        public JsonInheritanceConverter()
        {
            var attribute = System.Reflection.CustomAttributeExtensions.GetCustomAttribute<JsonInheritanceConverterAttribute>(typeof(TBase));
            _discriminatorName = attribute?.DiscriminatorName ?? "discriminator";
        }

        public JsonInheritanceConverter(string discriminatorName)
        {
            _discriminatorName = discriminatorName;
        }

        public string DiscriminatorName { get { return _discriminatorName; } }

        public override TBase Read(ref System.Text.Json.Utf8JsonReader reader, System.Type typeToConvert, System.Text.Json.JsonSerializerOptions options)
        {
            var document = System.Text.Json.JsonDocument.ParseValue(ref reader);
            var hasDiscriminator = document.RootElement.TryGetProperty(_discriminatorName, out var discriminator);
            var subtype = GetDiscriminatorType(document.RootElement, typeToConvert, hasDiscriminator ? discriminator.GetString() : null);

            var bufferWriter = new System.IO.MemoryStream();
            using (var writer = new System.Text.Json.Utf8JsonWriter(bufferWriter))
            {
                document.RootElement.WriteTo(writer);
            }

            return (TBase)System.Text.Json.JsonSerializer.Deserialize(bufferWriter.ToArray(), subtype, options);
        }

        public override void Write(System.Text.Json.Utf8JsonWriter writer, TBase value, System.Text.Json.JsonSerializerOptions options)
        {
            if (value != null)
            {
                writer.WriteStartObject();
                writer.WriteString(_discriminatorName, GetDiscriminatorValue(value.GetType()));

                var bytes = System.Text.Json.JsonSerializer.SerializeToUtf8Bytes((object)value, options);
                var document = System.Text.Json.JsonDocument.Parse(bytes);
                foreach (var property in document.RootElement.EnumerateObject())
                {
                    property.WriteTo(writer);
                }

                writer.WriteEndObject();
            }
            else
            {
                writer.WriteNullValue();
            }
        }

        public string GetDiscriminatorValue(System.Type type)
        {
            var jsonInheritanceAttributeDiscriminator = GetSubtypeDiscriminator(type);
            if (jsonInheritanceAttributeDiscriminator != null)
            {
                return jsonInheritanceAttributeDiscriminator;
            }

            return type.Name;
        }

        protected System.Type GetDiscriminatorType(System.Text.Json.JsonElement jObject, System.Type objectType, string discriminatorValue)
        {
            if (discriminatorValue != null)
            {
                var jsonInheritanceAttributeSubtype = GetObjectSubtype(objectType, discriminatorValue);
                if (jsonInheritanceAttributeSubtype != null)
                {
                    return jsonInheritanceAttributeSubtype;
                }

                if (objectType.Name == discriminatorValue)
                {
                    return objectType;
                }

                var typeName = objectType.Namespace + "." + discriminatorValue;
                var subtype = System.Reflection.IntrospectionExtensions.GetTypeInfo(objectType).Assembly.GetType(typeName);
                if (subtype != null)
                {
                    return subtype;
                }
            }

            throw new System.InvalidOperationException("Could not find subtype of '" + objectType.Name + "' with discriminator '" + discriminatorValue + "'.");
        }

        private System.Type GetObjectSubtype(System.Type baseType, string discriminatorValue)
        {
            foreach (var attribute in System.Reflection.CustomAttributeExtensions.GetCustomAttributes<JsonInheritanceAttribute>(System.Reflection.IntrospectionExtensions.GetTypeInfo(baseType), true))
            {
                if (attribute.Key == discriminatorValue)
                    return attribute.Type;
            }

            return null;
        }

        private string GetSubtypeDiscriminator(System.Type objectType)
        {
            foreach (var attribute in System.Reflection.CustomAttributeExtensions.GetCustomAttributes<JsonInheritanceAttribute>(System.Reflection.IntrospectionExtensions.GetTypeInfo(objectType), true))
            {
                if (attribute.Type == objectType)
                    return attribute.Key;
            }

            return null;
        }
    }



    [System.CodeDom.Compiler.GeneratedCode("NSwag", "14.3.0.0 (NJsonSchema v11.2.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class ApiException : System.Exception
    {
        public int StatusCode { get; private set; }

        public string? Response { get; private set; }

        public System.Collections.Generic.IReadOnlyDictionary<string, System.Collections.Generic.IEnumerable<string>> Headers { get; private set; }

        public ApiException(string message, int statusCode, string? response, System.Collections.Generic.IReadOnlyDictionary<string, System.Collections.Generic.IEnumerable<string>> headers, System.Exception? innerException)
            : base(message + "\n\nStatus: " + statusCode + "\nResponse: \n" + ((response == null) ? "(null)" : response.Substring(0, response.Length >= 512 ? 512 : response.Length)), innerException)
        {
            StatusCode = statusCode;
            Response = response;
            Headers = headers;
        }

        public override string ToString()
        {
            return string.Format("HTTP Response: \n\n{0}\n\n{1}", Response, base.ToString());
        }
    }

    [System.CodeDom.Compiler.GeneratedCode("NSwag", "14.3.0.0 (NJsonSchema v11.2.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class ApiException<TResult> : ApiException
    {
        public TResult Result { get; private set; }

        public ApiException(string message, int statusCode, string? response, System.Collections.Generic.IReadOnlyDictionary<string, System.Collections.Generic.IEnumerable<string>> headers, TResult result, System.Exception? innerException)
            : base(message, statusCode, response, headers, innerException)
        {
            Result = result;
        }
    }

}

#pragma warning restore  108
#pragma warning restore  114
#pragma warning restore  472
#pragma warning restore  612
#pragma warning restore 1573
#pragma warning restore 1591
#pragma warning restore 8073
#pragma warning restore 3016
#pragma warning restore 8600
#pragma warning restore 8602
#pragma warning restore 8603
#pragma warning restore 8604
#pragma warning restore 8625